### ISSUE TITLE
Duplicated content when using @import

### ISSUE THREAD

**Issue by naugtur** [webpack-contrib/less-loader#100]
In a build with @import of a shared file, less-loader will paste the content of imported file into all items that depended on it.

It also happens when using `extract-text-webpack-plugin` - the resulting file contains copies of imported file.

I noticed this when migrating from sass to less - this was not an issue with sass loader

**Comment by naugtur** [comment]
https://github.com/jtangelder/sass-loader/blob/master/index.js#L251 looks related

**Comment by naugtur** [comment]
Update: because of the way sass `extend` works it was harder to notice it. sass does it too.

I was used to building less/sass separately as a whole structure instead of importing it to js and extracting. Is this the desired behavior here?

**Comment by michael-ciniawsky** [comment]
Duplicate of #7
