### ISSUE TITLE
@import "~aptr-uikit/scr/index.less"; not working

### ISSUE THREAD

**Issue by alvarosaavedra** [webpack-contrib/less-loader#101]
It gives and error 
`ERROR in ./~/css-loader!./~/less-loader!./src/styles/app.less
Module build failed: Cannot resolve module 'aptr-uikit/scr/index.less' in /home/asasd/asdsad/frontend-locations/src/styles`

The file exists in node_modules, and the relevan part of the config of the webpack is:

```
 resolve: {
    modulesDirectories: ["node_modules"]
  },

  module: {
    loaders: [
      { test: /\.js?$/,
        loader: 'babel',
        exclude: path.join(__dirname, 'node_modules') },
      { test: /\.scss?$/,
        loader: 'style!css!sass',
        include: path.join(__dirname, 'src', 'styles') },
      { test: /\.less?$/,
        loader: 'style!css!less',
      },
      { test: /\.png$/,
        loader: 'file' },
      { test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
        loader: 'file'}
    ]
  }
```

Any help or advice????

**Comment by michael-ciniawsky** [comment]
`'aptr-uikit/scr/index.less'` => `'-> ~ <-aptr-uikit/scr/index.less'`
