### ISSUE TITLE
Disable image url resolution

### ISSUE THREAD

**Issue by arvinsim** [webpack-contrib/less-loader#110]
I have a LESS file that has background-image attributes pointing to images that do not exist in the same repository. Those images are provided by the website when it loads the LESS file.

The problem with this approach is that less-loader won't parse the LESS file and refuse to emit the CSS file if some images don't resolve. I get this error

`Module not found: Error: Cannot resolve 'file' or 'directory' ./img/arrow-up-gray.png`

Is there way to make it so that the less-loader doesn't try to resolve these urls and simply convert LESS to CSS?

**Comment by DNFcode** [comment]
Try to add `url` parameter to css-loader. Like this:
`"loader: "style!css?url=false!less"`

**Comment by bdthemes** [comment]
Hello @arvinsim, same problem me too.

```
ERROR in ./~/css-loader!./~/less-loader/lib/loader.js!./less/theme.less
    Module not found: Error: Can't resolve './images/cbp-sprite.png' in 'D:\xampp\htdocs\orphan\wp-content\themes\orphan\less'
    resolve './images/cbp-sprite.png' in 'D:\xampp\htdocs\orphan\wp-content\themes\orphan\less'
      using description file: D:\xampp\htdocs\orphan\wp-content\themes\orphan\package.json (relative path: ./less)
      after using description file: D:\xampp\htdocs\orphan\wp-content\themes\orphan\package.json (relative path: ./less)
        using description file: D:\xampp\htdocs\orphan\wp-content\themes\orphan\package.json (relative path: ./less/images/cbp-sprite.png)
          no extension
            D:\xampp\htdocs\orphan\wp-content\themes\orphan\less\images\cbp-sprite.png doesn't exist
          .js
            D:\xampp\htdocs\orphan\wp-content\themes\orphan\less\images\cbp-sprite.png.js doesn't exist
          .json
            D:\xampp\htdocs\orphan\wp-content\themes\orphan\less\images\cbp-sprite.png.json doesn't exist
          as directory
            D:\xampp\htdocs\orphan\wp-content\themes\orphan\less\images\cbp-sprite.png doesn't exist
```


 can you help me? my code is:

```
{
        test: /\.less$/,
        exclude: /node_modules/,
        use: extractLESS.extract([ 'css-loader', 'less-loader' ])
      },
```

so how to add url false option here?

**Comment by jhnns** [comment]
The less-loader does not try to resolve images. If they can't be found, that's no problem. But the css-loader is doing that. In fact, it's the purpose of using the css-loader. If you just want to turn your CSS code into a CommonJS module, you can use the [raw-loader](https://github.com/webpack-contrib/raw-loader).

I don't know why you would want to use the css-loader, if you turn of url resolution, but @DNFcode 's advice is also valid.

**Comment by jhnns** [comment]
@bdthemes with webpack 2 and the latest extract-text-webpack-plugin (`2.x.x`), you can configure it like this:

```javascript
module.exports = {
    ...
    module: {
        rules: [{
            test: /\.less$/,
            use: extractLess.extract({
                use: [{
                    loader: "css-loader",
                    options: { url: false }
                }, {
                    loader: "less-loader"
                }],
                // use style-loader in development
                fallback: "style-loader"
            })
        }]
    },
    plugins: [
        extractLess
    ]
};
```

With webpack 1 and the old extract-text-webpack-plugin, you'd write:

```js
    {
        test: /\.less$/,
        exclude: /node_modules/,
        use: extractLESS.extract([ 'css-loader?' + JSON.stringify({ url: false }), 'less-loader' ])
      },
```

**Comment by bdthemes** [comment]
Thank you @jhnns it's working 😄
