### ISSUE TITLE
Plugin syntax for Webpack v2

### ISSUE THREAD

**Issue by josh18** [webpack-contrib/less-loader#115]
```js
var LessPluginCleanCSS = require('less-plugin-clean-css');

module.exports = {
  ...
  lessLoader: {
    lessPlugins: [
      new LessPluginCleanCSS({advanced: true})
    ]
  }
};
```

This code doesn't seem to work in Webpack v2, any idea what the correct syntax should be? Currently I get this error message:
```
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
```

**Comment by SpaceK33z** [comment]
One of these should work (note: untested, don't have the time):

```js
test: /\.less$/,
use: [{
    loader: 'less-loader',
    options: {
        lessPlugins: [...]
    },
}
```

```js
test: /\.less$/,
use: [{
    loader: 'less-loader',
    options: {
        config: { lessPlugins: [...] }
    },
}
```

**Comment by josh18** [comment]
Tested those and still can't get it to work unfortunately. No error messages, just doesn't seem to do anything.

What are you expecting inside `lessPlugins: [...]`? `new LessPluginCleanCSS()`? I've also tried `'cleanCss'` and `'less-plugin-clean-cs'`.

My uneducated guess is that `options` gets converted to JSON so the plugin instance doesn't get transferred and the less loader is expecting an instance. But I don't really know how any of this works so I am probably wrong.

**Comment by SpaceK33z** [comment]
> My uneducated guess is that options gets converted to JSON so the plugin instance doesn't get transferred and the less loader is expecting an instance. 

No, that was the case in webpack v1. Since v2 the `options` don't get serialized. Unfortunately I don't know any other way. You could place some logs in `node_modules/less-loader/index.js` to find out where it fails.

**Comment by josh18** [comment]
Are you sure it works like that? I have somewhat got it working by changing `this.options` -> `config` [here](https://github.com/webpack/less-loader/blob/master/index.js#L50-L51) and then making my config look like this:
```js
loader: 'less-loader',
options: {
    lessLoader: {
        lessPlugins: [
            new LessPluginAutoprefix(),
            new LessPluginCleanCSS()
        ]
    }
}
```
However I get the error message `plugin.install is not a function` when I try to run it.

When I test `config[configKey].lessPlugins[0] instanceof LessPluginAutoprefix` it is false. `config[configKey].lessPlugins[0]` is an object of the options that I passed in my config so it exists, it just looks like it has been flattened.

If I force it something like `config[configKey].lessPlugins[0] = new LessPluginAutoprefix()` it works perfectly. I'm using the latest version of the webpack beta.

**Comment by josh18** [comment]
This is one way we could fix it, add this after line 49:
```js
config.plugins = config.plugins.map(function(plugin) {
    let pluginObject = require(plugin.name);

    // If the plugin returns a function we need to call it before we pass it on
    if (typeof pluginObject === 'function') {
        if (plugin.options) {
            return new pluginObject(plugin.options);
        } else {
            return new pluginObject();
        }
    }

    return pluginObject;
});
```
and then the config would be:
```js
options: {
    plugins: [
        {
            name: 'less-plugin-autoprefix'
        },
        {
            name: 'less-plugin-clean-css',
            options: {
                advanced: true
            }
        }
    ]
}
```
Thoughts?

**Comment by josh18** [comment]
Sorry, I know you are busy but are you able to have a quick look at the above and let me know if you want me to create a pull request?

Or if that solution doesn't look good let me know what direction you want to head in and I'll see what I can do.

**Comment by wujohns** [comment]
issue [#128](https://github.com/webpack/less-loader/issues/128) has the solution,But you need to use webpack.LoaderOptionsPlugin method to set the param `lessPlugins`.It is caused by the param parsing  strategy of webpack. Maybe we should add a issue to webpack(2.x)

**Comment by josh18** [comment]
Closing, the correct syntax is something like:
```js
const lessPluginAutoPrefix = require('less-plugin-autoprefix');

test: /\.less$/,
use: [{
    loader: 'less-loader',
    options: {
        plugins: [new lessPluginAutoPrefix({browsers: ['last 2 versions']})]
    },
}, ...]
```
(`options.plugins` instead of `options.lessPlugins`)

**Comment by bazineta** [comment]
@josh18 While this is closed, I'd love to know how you got past the `plugin.install is not a function` issues with this syntax.

**Comment by josh18** [comment]
@bazineta Sorry I don't think I ever got that issue. Make sure you look at the docs for the plugin you are using and check that you are using the correct syntax. Some will be `new lessPluginEtc(options)` and I believe others are just `lessPlugin`.

**Comment by bazineta** [comment]
@josh18 I suspect you might be using a version that works; in my testing of 3.0.0, this just does not seem to work at all, nor is the documentation in the README even accurate; 'lessPlugins' does absolutely nothing, though this was all merged just 5 days ago. Using 'plugins' does at least seem to use the plugins, but there seems no way to move beyond the `plugin install is not a function` issues.

**Comment by bazineta** [comment]
Unless I'm mistaken here, the issue is that while one can specify less plugins using `plugins` (not `lessPlugins`), the loader blindly overwrites any `install` function in the plugin, resulting in arguments never actually being applied to the plugins. Thus, you can run them, but you can't pass arguments to them.

**Comment by josh18** [comment]
Can you post your webpack config and relevant node module versions?

**Comment by bazineta** [comment]
Relevant module versions are all the latest released:
```
    "extract-text-webpack-plugin": "2.1.0",
    "less": "2.7.2",
    "less-loader": "3.0.0",
    "less-plugin-autoprefix": "1.5.1",
    "less-plugin-clean-css": "1.5.1",
    "webpack": "2.2.1",
```
My webpack config is very large, but the relevant portions are (with apologies in advance to those who can't stand CoffeeScript):
```
LessPluginAutoPrefix = require 'less-plugin-autoprefix'
LessPluginCleanCSS   = require 'less-plugin-clean-css'

lessPluginAutoPrefix = new LessPluginAutoPrefix()
lessPluginCleanCSS   = new LessPluginCleanCSS keepSpecialComments: 0

 module:
      rules: [
        {
          test: /\.less$/,
          use: ExtractTextPlugin.extract
            fallback: 'style-loader'
            use: [
              'css-loader'
              {
                loader: 'less-loader'
                options:
                  lessPlugins: [
                    lessPluginAutoPrefix
                    lessPluginCleanCSS
                  ]
                }
            ]
        }
    ]
```
This is using the as-documented `lessPlugins`. If using `plugins`, it'll fail with `plugin.install is not a function` due to the `cloneDeep()` calls wiping anything that's not an array or an object from the plugins; i.e., farewell, `install`, we barely knew you.

**Comment by josh18** [comment]
Just checked and I'm on 2.2.3. Try downgrading (and then use my syntax) and see if it works?

My guess is that they broke something on 3.0.0, if so I would suggest opening a new issue.

**Comment by bazineta** [comment]
Thanks for checking. I'll open a new issue.

**Comment by bazineta** [comment]
Opened #161.
