### ISSUE TITLE
Exclude file from less loader

### ISSUE THREAD

**Issue by krazi3** [webpack-contrib/less-loader#116]
I am using bootstrap with less .. the default bootstrap less file comes with glyphicons 

![image](https://cloud.githubusercontent.com/assets/6938697/20343228/5f6bb932-ac0f-11e6-980b-bf25f36dcff9.png)

I dont want to include glyphicons in my project ... for now i have made a loader which removes the glyphicons.less line from the bootstrap.less file.

![image](https://cloud.githubusercontent.com/assets/6938697/20343330/ba3fa5ee-ac0f-11e6-8b5e-a4fb98998d9d.png)

I wanted to know that is there any way to this using less-loader.

I tried to use webpack `resolve.alias`.

**Comment by evilebottnawi** [comment]
Out of scope loader, just don't import `glyphicons.less`
