### ISSUE TITLE
Nested local rules not supported

### ISSUE THREAD

**Issue by vaskevich** [webpack-contrib/less-loader#120]
I'm using less-loader with css-loader, and set up style sheets like this:

```
local {
  .classA {
    color: blue;

    .classB & {
      color: red;
    }
  }
}
```

The end result is that, after using css-loader, I get rules like this:

```.classB .some-prefix--classA--aq9392 { ... }```

The issue it seems is that less-loader ends up generating output like this:

```.classB local: .classA { ... }```

Instead, it seems that `local:` should be placed at the beginning when there are nested selectors.

Can this be fixed? Thanks!

**Comment by vaskevich** [comment]
BUMP!

**Comment by jhnns** [comment]
> Can this be fixed? 

No. This is how the capture selector `&` is defined in Less (and Sass). The less-loader does not change language semantics.

**Comment by jhnns** [comment]
Since you're using the `:local` selector, I assume you're also using CSS modules. With CSS modules, nesting selectors becomes an anti-pattern imho.
