### ISSUE TITLE
less-loader will filter `\`

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/less-loader#123]
This is my less code:
`a { &:after { content: "\A"; white-space: pre; } }`
This is compiled css code:
`a:after { content: "A"; white-space: pre; }`

And I use \,this is my less code:
`a { &:after { content: "\\A"; white-space: pre; } }`
This is compiled css code:
`a:after { content: "\\A"; white-space: pre; }`
Why filter single backslash？

I tried sass-loader.It has problem that same

**Moved from https://github.com/webpack/webpack/issues/2573**

**Comment by michael-ciniawsky** [comment]
I guess this happens in  `css-loader` there was something and `sass-loader` seems to be affected aswell

**Comment by evilebottnawi** [comment]
Fixed on `css-loader` side
