### ISSUE TITLE
Import of less file with configuration approach not working?

### ISSUE THREAD

**Issue by dschulten** [webpack-contrib/less-loader#124]
I am new to less-loader and I have trouble with the configurative approach for less-loader.

I installed the css, style and less loader with --save-dev. In my main.js I can use an inline statement like

    import css from 'style-loader!css-loader!less-loader!./file.less';

so that webpack processes my /src/file.less and inserts the corresponding css into the  html head.

However when I want to use the configuration approach and add the suggested configuration

```
{
        test: /\.less$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } }
          'less-loader'
        ]
      }
```
and change the import statement to 

    import css from 'file.less';    

I get a build error

    Cannot resolve module 'file.less' in ...path to my src...

If I read the build output messages correctly, the less-loader never gets to processing the less file.

**Comment by BlaM** [comment]
You may have to specify a path ("./"):

    import css from './file.less';    

However if I do that I end up with:

    Module parse failed: /full-path-omitted/file.less Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.

**Comment by BlaM** [comment]
I guess the solution is quite simple. The "module.rules" syntax is for webpack 2, but when you install webpack from NPM you still get [webpack 1.14.0](https://www.npmjs.com/package/webpack).
