### ISSUE TITLE
The param 'LessPlugins' can't work

### ISSUE THREAD

**Issue by wujohns** [webpack-contrib/less-loader#128]
When configing webpack(2.x) and use less-loader like below:
```
{
  test: /\.less$/,
  use: [
    'style-loader',
    { loader: 'css-loader', options: { importLoaders: 1 } },
    {
      loader: 'less-loader',
      options: { LessPlugins: new lessPluginAutoPrefix({ cascade: true, browsers: ["last 5 versions"] }) }
    }
}
```
The plugin will not work unless config it like this below:
```
plugins: [
  new webpack.LoaderOptionsPlugin({
    options: {
        lessLoader: {
           lessPlugins: [
              new lessPluginAutoPrefix({ cascade: true, browsers: ["last 5 versions"] })
           ]
       }
   }
 })
]
```
I read the code in less-loader and find the cause in the index.js
file:less-loder/index.js
line:50
```
// If present, add custom LESS plugins.
if (this.options[configKey]) {
	config.plugins = config.plugins.concat(this.options[configKey].lessPlugins || []);
}
```
and the `configKey`  is default `lessPlugins`

**Comment by wujohns** [comment]
I find It's too hard for me after get this problem is related to the webpack.LoaderOptionsPlugin(it add some function to the less plugins).

**Comment by artemkaint** [comment]
works for me if i set 
```{
            loader: 'less-loader',
            options: {
              ident: 'less',
              outputStyle: 'expanded',
              sourceMap: true,
              relativeUrls: false,
              plugins: [lessAbsoluteUrlsPlugin]
            }
   },```
instead of lessPlugins

**Comment by neekey** [comment]
@artemkaint You solution does not work for me, mine:

```
{
            loader: 'less-loader',
            options: {
              plugins: [
                new RewriteImportPlugin({
                  paths: {
                    '../../theme.config':  __dirname + '/app/semantic-ui/theme.config',
                  },
                }),
              ],
            },
          },
```

Can you clarify what should be like inside the `plugins`?

**Comment by artemkaint** [comment]
@neekey  You haven't set "ident: 'something'" in params& It's important to new webpack params setting

**Comment by neekey** [comment]
@artemkaint thanks for your reply, but I don't understand the `ident` thing, can you give more detail about it?

**Comment by jhnns** [comment]
`lessPlugins` was outdated, it's just `plugins`. I fixed it in the README.

**Comment by rhrn** [comment]
i find solution here for me:
http://neekey.net/2016/12/09/integrate-react-webpack-with-semantic-ui-and-theming/
