### ISSUE TITLE
The 'Sourcemaps' configuration doesn't work.

### ISSUE THREAD

**Issue by sdhhqb** [webpack-contrib/less-loader#129]
I follow the [Sourcemaps configuration](https://github.com/webpack/less-loader#sourcemaps) in the README.md, but it doesn't work. 
```
module: {
    rules: [  //should this be loader?
      {
        test: /\.less$/,
        use: ExtractTextPlugin.extract(  // pass params to extract this way seems wrong
          fallbackLoader: 'style-loader',
          loaders: [
            // activate source maps via loader query
            {
              loader: 'css-loader',
              options: { sourceMap: true, importLoaders: 1 }
            }  // missing comma
            {
              loader: 'less-loader',
              options: { sourceMap: true }
            }
          ]
        )
      }
    ]
  }
```
After poke around for a while, I changed my loader configuration to this,
```
{
	test: /\.less$/,
	loader: ExtractTextPlugin.extract(
		'style-loader',
		[
			'css?sourceMap=true',
			'less?sourceMap=true'
		]
	)
}
```
and it worked.

I'm a little confused about this configuration, is it out of date? Could you guys update this configuration to the newest way.

**Comment by jeroenschieven** [comment]
Are you using Webpack 1? Rules is only available in Webpack 2.

https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules

**Comment by sdhhqb** [comment]
Now this is no longer a problem. I haven't migrate to webpack 2 at that time.
