### ISSUE TITLE
Webpack less plugin slows down compilation

### ISSUE THREAD

**Issue by pawelpabich** [webpack-contrib/less-loader#137]
Hi,

I'm trying to migrate a Gulp build to Webpack. During that exercise I noticed that my less compilation is very slow. 

The first problem was cased by [extract text plugin](https://github.com/webpack/extract-text-webpack-plugin/issues/217).

The second one seems to be caused by [Webpack less plugin](https://github.com/webpack/less-loader/blob/master/index.js#L46-L47). If I remove it then the compilation time drops from 2.5sec to 1.8sec and my site still works. I'm not entirely sure why this plugin is needed but would it make sense to add an option to skip it? 

What do you think?

**Comment by jhnns** [comment]
I'm currently working on that to allow you to disable the plugin if you're not interested in using webpack's resolver. See #169
