### ISSUE TITLE
README wrong example

### ISSUE THREAD

**Issue by renatobenks** [webpack-contrib/less-loader#139]
# Example webpack.config.js:

I saw a example in README showing how use plugin for sourcemaps with `less-loader`, but I think that this example, seems to me wrong, because this:

```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  // must be 'source-map' or 'inline-source-map'
  devtool: 'source-map',
  module: {
    rules: [{
        test: /\.less$/,
        use: ExtractTextPlugin.extract(
          fallbackLoader: 'style-loader',
          loaders: [ ]
        )
      }]
  }
}
```

> Where call method `extract` on `ExtractTextPlugin` variable, It's passed argument with notation object javascript, but no like a object javascript, so this example, couldn't be implemented.

I did PR for fix this example, so if I'm right, this can be fixed. #140

**Comment by fhqdgv** [comment]
+1
