### ISSUE TITLE
globalVars config does not work at all

### ISSUE THREAD

**Issue by dyf19118** [webpack-contrib/less-loader#158]
### error:
 Module build failed: variable @work-dir is undefined
near lines:
  /* variable work-dir is defined as a less compile option in globalVars */

  @cmpt: '@{work-dir}/cmpt/public/less';
  @cmpt-images: '/cmpt/public/img';

### environment:
webpack v2.2.1
less-loader v3.0.0
vue-loader v11.1.4
extract-text-webpack-plugin v2.1.0

### code:
here's piece of my code of webpack loaders config.
```js
const lessConfig = {
	globalVars: {
		'work-dir': path.resolve('src/main/webapp'),
	},
};				
const loaders = [
	{
		test: /\.hbs$/,
		loader: "handlebars-loader",
	},
	{
		test: /\.vue$/,
		loader: 'vue-loader',
		options: {
			loaders: {
				less: ExtractTextPlugin.extract({
					fallback: 'vue-style-loader',
					use: ['css-loader', `less-loader?${JSON.stringify(lessConfig)}`],
				}),
				js: ['babel-loader', 'eslint-loader?parser=babel-eslint'],
			}
		}
	},
];
```

If i omit the query string, the same error is thrown as expected.
I also tried the globalVar syntax, which is like  'less-loader?globalVar=name=value', but failed.
Any help, thanks.

**Comment by jhnns** [comment]
Maybe you need to surround the path of `work-dir`with double quotes, I don't know. Please create a minimal test repository that makes reproducing the problem easy. You probably don't need the ExtractTextPlugin to reproduce it. for instance.

**Comment by dyf19118** [comment]
@jhnns I've tried the minimum demo and it works.Then i found it's a problem caused by extract-text-webpack-plugin when it can't work as normal(probably it defers some work of less-loader).

**Comment by cihadhoruzoglu** [comment]
@dyf19118 could you share your solution? I have the same problem.

**Comment by jhnns** [comment]
I assume, this is related to the vue-loader, because it is not obvious how the less options are passed to the less-loader. Unfortunately, there is also no explanation in their docs how to accomplish this.

I assume, that it would be possible to pass the options as query string (webpack 1 style), like this:

```js
{
        test: /.vue$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "vue-loader",
            options: {
              loader: "less-loader?" + JSON.stringify({
                globalVars: {
                  website: process.env.WEBSITE
                }
              })
            }
          },
          { loader: "eslint-loader" }
        ]
      }
```

but this is not ideal since you cannot stringify all possible options, like Less plugins. That's why we switched to the new loader configuration in webpack 2.

Please file an issue at the vue-loader and ask them how to apply custom configuration to loaders.

**Comment by dyf19118** [comment]
try this. @cihadhoruzoglu 

### definitions
```js
// return value of getLessConfig is like
/*
{
	globalVars: {
		'work-dir': `"some value wrapped by quotes"`,
	},
}
*/
// attention: if less variable is a string value, you should wrap it with double quotes
// with es6 template syntax: `"string value"`
// with es5 or under syntax: JSON.stringify("string value")

const lessConfig = getLessConfig();
const lessLoader = `less-loader?${JSON.stringify(lessConfig)}`;
const vueLessLoader = ['vue-style-loader', 'css-loader', lessLoader];
```
### configuration
```js
{
	test: /\.vue$/,
	loader: 'vue-loader',
	options: {
		loaders: {
			less: vueLessLoader,
			js: ['babel-loader', 'eslint-loader?parser=babel-eslint'],
		}
	}
}
```
