### ISSUE TITLE
 webpack can't resolve 'less-loader' with less-loader@4.0.0 but works with less-loader@3.0.0

### ISSUE THREAD

**Issue by atkawa7** [webpack-contrib/less-loader#177]
I am having problems with the new release. Here is the error I am getting 'Module not found: Error: Can't resolve 'less-loader' in' but if I install less-loader@3.0.0 it works fine

**Comment by adi-pjackson** [comment]
Just ran into the same issue. In 4.0.0 the packages "main" file is `dist/cjs.js`, but that file doesn't exist in the `dist` folder.
Should it be `dist/index.js` instead?

**Comment by bazineta** [comment]
#161

**Comment by ersimont** [comment]
@bazineta I looked through that issue you linked, but I didn't gain much from it. Did you link it to say that "this is also mentioned in another place", or to say "see this other place for a workaround", or something else?

**Comment by bazineta** [comment]
@ersimont Sorry, should have left more detail there, but was running out the door at the time. Third to last comment in #161, about 7 hours ago, same issue.

**Comment by unauthorized-401** [comment]
+1

**Comment by BooleT37** [comment]
+1

**Comment by jhnns** [comment]
I messed this up ^^

Thx for reporting this 👍 should be fixed
