### ISSUE TITLE
NormalModuleReplacementPlugin has no effect with less-loader@4

### ISSUE THREAD

**Issue by snadn** [webpack-contrib/less-loader#184]
there is 3 files, a.less b.less c.less
 a import b, and i use NormalModuleReplacementPlugin to replace b to c

when i use webpack@1 and less-loader@2, b is replaced by c.

but, upgrade to webpack@2 and less-loader@4, nothing happend

**Comment by jhnns** [comment]
Hi, thanks for the bug report. It would be a big help if you could provide a minimal test repository that demonstrates the problem so I can check that out. Try to remove as much stuff as possible since it helps tracking down the problem.

**Comment by snadn** [comment]
@jhnns here is the demo https://github.com/snadn/less-loader-test

**Comment by snadn** [comment]
Hey, what's the status on this?

**Comment by Biktop** [comment]
I confirm that NormalModuleReplacementPlugin doesn't work correctly in less-loader@4 but it works in v3.0.0.

**Comment by zombieJ** [comment]
Currently Ant Design provides theme less file. User can use `modifyVars` to replace.
But we wish there have a better way to replace hole theme less instead of variable config.

Seems `NormalModuleReplacementPlugin` is a better solution. It should re-consider of this PR: #216

cc @michael-ciniawsky

**Comment by cap-Bernardito** [comment]
`NormalModuleReplacementPlugin` is not intended for your purposes, and is no longer supported by `less-loader`. Use it instead of aliases.
