### ISSUE TITLE
webpack v2 introduce less plugin error

### ISSUE THREAD

**Issue by MallTo-Silence** [webpack-contrib/less-loader#200]
Use webpack templates created with vue-cli, configuration less plugin is reported incorrectly.

Code:
```
{
  test: '/\.less$/'.
  use: [{
      loader: 'css-loader',
    },
    {
      loader: 'less-loader',
      options: {
        paths: [path.resolve(__dirname, "../src/assets/style")],
        plugins: [
          require('less-plugin-functions')
        ]
      }
    }
  ]
}
```

use 'require('less-plugin-functions') '
```
Cannot read property 'install' of null
      in undefined (line undefined, column undefined)
```

use new (require('less-plugin-functions'))()
```
 Plugin.install is not a function
       in undefined (line undefined, column undefined)
```

package.json: 
```
    "less": "^2.7.2",
    "less-loader": "^4.0.3",
    "less-plugin-functions": "^1.0.0",
```

**Comment by duzun** [comment]
I have a similar issue with `less-plugin-lists`.

Any ideas why is it happening?

**Comment by Femonzor** [comment]
i have succeeded to transform `px` to `rem` with `less-plugin-functions` in `webpack`. the version of less, less-loader, less-plugin-functions are same as yours. and my `webpack` is configured like this:
```
module.exports = {
    ...,
    module: {
        loaders: [{
            test: /\.vue$/,
            loader: "vue-loader",
            options: {
                loaders: {
                    less: ExtractTextWebpackPlugin.extract({
                        fallback: "vue-style-loader",
                        use: "css-loader!autoprefixer-loader!less-loader"
                    })
                }
            }
        }, {
            test: /\.less$/,
            exclude: /^node_modules$/,
            loader: ExtractTextWebpackPlugin.extract({
                fallback: "style-loader",
                use: [{
                    loader: "css-loader"
                }, {
                    loader: "autoprefixer-loader"
                }, {
                    loader: "less-loader",
                    options: {
                        plugins: [
                            new LessPluginFunctions()
                        ]
                    }
                }]
            })
        },
        ...
    },
    ...
}
```
hope it will help u :)

**Comment by bq-hentai** [comment]
I have the same problem, too.

And today, I found that the loader get options via `loader-utils.getOptions`, and the query is `?{"plugins":[{}],"sourceMap":false}`. Of course, it can't get the correct plugins.

As I am not familiar to webpack, I don't know how to fix this now OTL

**Comment by michael-ciniawsky** [comment]
Try adding an `options.ident = 'less'` so the `{Function}` references are maintained when the loader options got stringified

**Comment by bq-hentai** [comment]
see [webpack doc](https://webpack.js.org/configuration/module/#rule-options-rule-query) for more detail.

**Comment by zzz999** [comment]
@bq-hentai How to solve the problem at last?

**Comment by bq-hentai** [comment]
@zzz999 I gave up... :(

**Comment by forguos** [comment]
vue-cli version2:   
  just like it  in util.js

const LessPluginFunctions = require('less-plugin-functions')

   return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less', {
        plugins: [ new LessPluginFunctions() ]
    }),
    sass: generateLoaders('sass', { indentedSyntax: true }),
    scss: generateLoaders('sass'),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }


and it works
