### ISSUE TITLE
Using enhanced require syntax in @import calls is not possible when using webpack resolver? Why not?

### ISSUE THREAD

**Issue by throwaway1496385509** [webpack-contrib/less-loader#205]
I've known for years that it's possible to use Webpack resolver with less-loader and thus I can take advantage of having loaders. Finally the day has come when I needed this feature, but turned out I can't just do 

```less
@import "../../path/to/loader!../path/to/file/to/process";
// Will be processed as "../../path/to/loader/path/to/file/to/process" and fail
```

I needed to process big json file and extract an array of classes from it for a future use in LESS code. As it's very specific to the project and type of that particular json file I felt it would be better to not add my custom loader to webpack configuration and just use `!`-separated require syntax. Since webpack is resolving files I expected that to work.

I already spoiled it above, but when [`loaderContext.resolve` here](/webpack-contrib/less-loader/blob/83837f7c12d/src/createWebpackLessPlugin.js#L42-L60) receives a string with exclamation points it just treats them as directory separators and looks for the wrong file in the wrong place.

Is there a good reason why it has been done like this or has it just been overlooked? 

Things would have been much easier if `loaderContext.loadModule` supported `context` on it's own, but similar behavior can be achieved by processing parts of require string separately. Here's modified version of `WebpackFileManager#loadFile`:

```js
loadFile(filename, currentDirectory /* , options, environment */) { // eslint-disable-line class-methods-use-this
    // Less is giving us trailing slashes, but the context should have no trailing slash
    const context = currentDirectory.replace(trailingSlash, '');
    const isALoader = /^[^.\/]*($|\?)/;
    let resolvedFilename;

    return Promise
        .all(
            filename.split('!').map((name, index, arr) => {
                const isLastSegment = index === arr.length - 1;
                let url = isLastSegment ? name.replace(matchMalformedModuleFilename, '$1') : name;

                if (isALoader.test(url) && !isLastSegment) {
                    return Promise.resolve(url);
                }

                return resolve(context, loaderUtils.urlToRequest(url, url.charAt(0) === '/' ? '' : null));
            })
        )
        .then(parts => {
            resolvedFilename = parts.join('!');

            if (parts.length === 1 && isLessCompatible.test(resolvedFilename)) {
                return readFile(resolvedFilename)
                    .then(contents => contents.toString('utf8'));
            }

            return loadModule([stringifyLoader, resolvedFilename].join('!'))
                .then(JSON.parse);
        })
        .then((contents) => {
            return {
                contents,
                filename: resolvedFilename,
            };
        });
}
```

It solves the problem, but be aware, this code is not without problems. Determining potential loaders with regular expression is sketchy and potentially error-prone, I don't think that's nearly the same as what webpack does internally. Also things will go wrong if one of the loaders is going to have exclamation mark in its query.

If someone more knowledgeable in webpack inner workings could fix it and submit as pull request I would really appreciate that. Well, unless there's a good reason to not have this feature in LESS code

**Comment by cap-Bernardito** [comment]
By default, the webpack does not process `!` - separated syntax in less - files.

Since this feature is needed in very rare cases and is not widely used, it is not planned to implement it in less-loader yet.

You can make this with `less` - plugins.

If you want this feature to be added in `less-loader`, please provide more use cases.
