### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by BartekIL** [webpack-contrib/less-loader#206]
Hello less community! 

I'm working on code splitting in my app and I've got problem with less. On the very beginning I'm loading all styles to one chunk (bootstrap, fontawesome, custom global variables etc.). Then in dynamically loaded js files I'd like to load unique styles for those js, for example: 
loader -> should import loader styles
But that loader styles uses bootstrap variables and each time when I'm comipling webpack it returns error that those variables cannot be resolved. Is there any option to handle global variables with less loader? So  can I import once whole file with globals which will have global scope for variables? Or method that will be inject variables for every module?

**Comment by throwaway1496385509** [comment]
I don't think so, however what you can do is require `~bootstrap/less/variables.less` in every file of yours. That should do it

**Comment by opatut** [comment]
I think you *could* write a custom loader that prepends the desired imports/variable definitions to the file content and use that loader before the less-loader. This would be very advanced webpack stuff though, probably doesn't really make sense to go this way in most cases. Also, manually importing the variables file is kind of more transparent to other developers.
