### ISSUE TITLE
fileLoader prevents less's @import from sharing variable/mixin context with imported less files

### ISSUE THREAD

**Issue by mattly** [webpack-contrib/less-loader#21]
for example:

```
@import "variables.less"; // declares variables
@import "mixins.less"; // declares mixins
@import "some_styles.less"; // declares styles, relies on variables / mixins
```

because the file loader is effectively compiling each sub-import individually, the context is not being shared. If I just delete the fileLoader method from the code and use the built-in one, it works as expected.

This is a problem because many third-party tools, libraries and themes rely on this mechanism and using them with webpack shouldn't require adapting them to the loader's peculiarities.

**Comment by jhnns** [comment]
Closing this one due inactivity.

With https://github.com/webpack-contrib/less-loader/pull/169 it will also be possible to disable webpack's resolver entirely.
