### ISSUE TITLE
Unexpected character '@' 

### ISSUE THREAD

**Issue by mladenp** [webpack-contrib/less-loader#211]
I am using less-loader 3.0.0 and less 2.7.2, Webpack 1 and when i have less file like this:
`@import "../../node_modules/antd/dist/antd.less"; ` i get "unexpected character '@'"
But if i add just something like: `@base-color: red;` it compiles fine.

I am using loader in webpack 1 like this:

`            {
                test: /\.css$/,
                loader: 'style-loader!css-loader'
            },
            {
                test: /\.less$/,
                loader: 'less-loader'
            },
`

**Comment by resistdesign** [comment]
I'm getting the same thing. https://github.com/resistdesign/rdx/issues/22

**Comment by Panoplos** [comment]
Try:
`{ test: /\.less$/, loader: 'style-loader!css-loader!less-loader' }`
