### ISSUE TITLE
import from scoped npm package cause error

### ISSUE THREAD

**Issue by guoerwei** [webpack-contrib/less-loader#214]
I use a "less" field in the package.json and add "less" to `resolve.mainFields` [#91](https://github.com/webpack-contrib/less-loader/issues/91)

It works fine at first, but when the package is a scoped npm package, I got an error

`Can't resolve "@some-scope/some-style-module.less" in ...`

Here is my code
```
@import "~@some-scope/some-style-module";
```

PS.
`@import "~@some-scope/some-style-module/src/index.less"` works

**Comment by michael-ciniawsky** [comment]
Please reopen this in `webpack/enhance-resolve`  eventually scoped packages aren't supported there yet. Feel free to reopen in case `enhance-resolve` isn't the culprit
