### ISSUE TITLE
How to Ignore node module directory that import via relative path.

### ISSUE THREAD

**Issue by aviram83** [webpack-contrib/less-loader#215]
So I want to exclude any less file that came from the node_modules directory.

my loader is simple:
```
loaders: [
  {
    test: /\.less$/,
    exclude: /node_modules/,
    loader: ExtractTextPlugin.extract('css?sourceMap!resolve-url-loader!postcss-loader!less?sourceMap')
  }
]
```

My file looks like this:

Simple.jsx
```javascript
import React from 'react';
import './style.less';

const Comp = () => (
    <div>
        Hello
    </div>
);

export default Comp;
```

style.less
```less
@import "~first-component/lib/FirstComponent.less";
@import "../../node_modules/second-component/lib/SecondComponent.less";

@import "components/views/Main/Main";
@import "components/views/HomePage/HomePage";
```

As long as I am testing my program (run a webpack dev server, with no exclude) everything work fine

But when I am building a package and I want to exclude those node_modules file only the static path work, the path with tilde (~) are ignored from the exclude and I can see them in the output css.

I have try to find a solution out there but came with empty hands, is there any?

thanks.

**Comment by evilebottnawi** [comment]
You can use `null-loader` for this case, please read docs https://github.com/webpack-contrib/less-loader/issues/7#issuecomment-69487144
