### ISSUE TITLE
Successfully set up the global variable, but npm run  build error

### ISSUE THREAD

**Issue by xuxiaoxiao312** [webpack-contrib/less-loader#218]
## error:
Module build failed: ModuleBuildError: Module build failed:
  text-align: center;
  color: @primary;
Variable @primary is undefined
      in D:\Code\pregnotice-webapp\src\components\ViewBox.vue (line 126, column 9)

## environment: 
  webpack: v2.2.1,
  less-loader: v4.0.5,
  vue-loader: v12.2.2,

### webpack.base.config.js:

```
const lessConfig = {
	globalVars: {
           "primary": "#9187FD"
	},
};
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
	      loaders: {
		less: ExtractTextPlugin.extract({
                      use:  ['css-loader', 'less-loader?'+JSON.stringify(lessConfig)}],
                      fallback: 'vue-style-loader'
                 })
	    }
        }
     ]
   }
```
when i do npm run dev ,It can run correctly,but when i do npm run build, it report errors
Any help, thanks.

**Comment by michael-ciniawsky** [comment]
Please reopen this issue in `vue-loader` instead, the sole `less-loader` part seems to be correct
