### ISSUE TITLE
Example for a typical 'gulp' workflow (less, css, concat, cssnano)

### ISSUE THREAD

**Issue by nocke** [webpack-contrib/less-loader#221]
An extended example under [master/examples](https://github.com/webpack-contrib/less-loader/tree/master/examples) would be great, that ...

- compile less→css
- merge in additional css
- apply cssnano to the complete chain
- output `styles.css` and `styles.css.map`

Since I'd say, this is a very if not the most common scenario. Having most stuff in less, but some 3rd party css, too, and wanting the cssnano-part on top. (And, I admit: I don't know how to do that.)

**Comment by cap-Bernardito** [comment]
You can see examples of typical configs using the links below in the `examples` section.

https://webpack.js.org/loaders/less-loader/#examples
https://webpack.js.org/loaders/css-loader/#pure-css-css-modules-and-postcss
