### ISSUE TITLE
Less extension is required in imports

### ISSUE THREAD

**Issue by acacha** [webpack-contrib/less-loader#223]
I'm not sure if this is a less issue or webpack/less-loader extension.

Please see issue: https://github.com/less/less.js/issues/3115

At least as reference I think this issue could be useful for less-loader community. YOu can reproduce the problem with this repo running npm run dev:

https://github.com/acacha/AdminLTETinkerLaravelMix

Take into account that this is maybe a webpack issue because using lessc command there are no problems.

**Comment by robhuzzey** [comment]
I can confirm this happens without webpack as demonstrated in the repo linked on https://github.com/less/less.js/issues/3115
