### ISSUE TITLE
Change url variables with modifyVars

### ISSUE THREAD

**Issue by sandro-csimas** [webpack-contrib/less-loader#224]
This is my webpack.config.js
````
module: {
  rules: [
    {
      test: /\.less$/,
      use: [
        {loader: 'style-loader'},
        {loader: 'css-loader'},
        {
          loader: 'less-loader',
          options: {
            modifyVars: {
              '@website': 'http://localhost:4000'
            }
          },
        },
      ],
      include: helpers.root('src/assets/styles'),
    },
  ],
},
````
variables.less
````
@fa-font-path:        "@website/assets/fonts/font-awesome";
...
````
This is the webpack output:
````
ERROR in ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js?{"modifyVars":{"@website":"http://localhost:4000"}}!./src/assets/styles/main.less
Module not found: Error: Can't resolve './font-awesome/@website/assets/fonts/font-awesome/fontawesome-webfont.eot?v=4.7.0' in '/home/sandro/lib-javascript/src/assets/styles'
 @ ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js?{"modifyVars":{"@website":"http://localhost:4000"}}!./src/assets/styles/main.less 6:772-864
 @ ./src/assets/styles/main.less
 @ ./src/lib.ts
 @ ./src/entry.ts
````
Webpack is trying to load the path ````./font-awesome/@website/assets/fonts/font-awesome/fontawesome-webfont.eot?v=4.7.0```` but this should be loaded as ````http://localhost:4000/assets/fonts/font-awesome/fontawesome-webfont.eot?v=4.7.0````.
How to make modifyVars work correctly in this case?

**Comment by michael-ciniawsky** [comment]
Is `@website`  an alias specified in `resolve.alias`? Those are not supported in this case

**Comment by sandro-csimas** [comment]
Sorry, I closed the issue by mistake.
@michael-ciniawsky, can I solve this problem using ````resolve.alias````?

**Comment by michael-ciniawsky** [comment]
Unfortunately, nope sry `resolve.alias` isn't supported for `@import`'s to my knowledge.`@website` needs to be replaced with the non-alias here

**Comment by treywood** [comment]
I'm a few months late, but just in case...

you don't need `@` in the variable name, and you need double quotes inside your single quotes since the value is a string:

```javascript
modifyVars: {
  'website': '"http://localhost:4000"'
}
```

Also, when you use the variable in your .less file, you need curly braces around the variable for interpolation:

```less
@fa-font-path:        "@{website}/assets/fonts/font-awesome";
```

**Comment by sandro-csimas** [comment]
Wow, it worked, @treywood. Many thanks!!!
