### ISSUE TITLE
[Feature] support `{String|Function}` input for hot reloading  (`options.modifyVars`)

### ISSUE THREAD

**Issue by stackjie** [webpack-contrib/less-loader#229]
webpack config
```js
{
  test: /\.less$/,
  loader: 'less-loader',
  options: {
     modifyVars: theme
   }
}
```
theme.js
```
module.exports = {
  '@primary-color ': '#4578c8',
  '@info-color': '#049df8',
  '@success-color': '#6ccb24',
  '@warning-color': '#ffb619',
  '@error-color': '#f30416',
  '@input-bg': '#fbfdfc',
  '@table-thead-bg': '@input-bg'
}
```
every change in theme.js I have to restart the server `npm run`😆，how to hot reload?
thanks

**Comment by michael-ciniawsky** [comment]
You can try for watch mode at least

**webpack.config.js**
```js
{
   test: /\.less$/
   use: [
      {
         loader: less-loader, 
         options: (loader) => {
             loader.addDependency('path/to/theme')

             return {
                modifyVars: theme
             }
         }
      }
   ]
}
```

But I'm not 💯, if it works with `less-loader`, this may require a PR to accept a `{Function}` for `modifyVars`

**webpack.config.js**
```js
{
   test: /\.less$/
   use: [
      {
         loader: less-loader, 
         options: {
           ident: 'less',
           modifyVars: (loader) => {
             loader.addDependency('path/to/theme')
            
             return require('path/to/theme')
           }
         }
      }
   ]
}
```

**Comment by stackjie** [comment]
@michael-ciniawsky Seems to not accept the `Function` for `options`?

**error info**
```
    throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[8].use should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
```

**Comment by michael-ciniawsky** [comment]
Yeah, that's what I meant  with 'maybe' 😞, we need to accept a `{Function}` for `modifyVars` and handle it inside the loader. if you want to go for it feel free to open a PR and I will help if needed, otherwise I will tackle it when time

**Comment by stackjie** [comment]
@michael-ciniawsky thanks😁

**Comment by tim-soft** [comment]
Anything I can do to help make this a reality? 
Designing themes via less loader's modifyVars is pretty painful without HMR support

**Comment by Aka4Code** [comment]
@michael-ciniawsky Do you plan to add hot reloading here?

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by evilebottnawi** [comment]
We implement `prependData` in next major release, it is same as `modifyVars` and it is support `Function`

**Comment by ButuzGOL** [comment]
Is there any information how can it be achieved ?
Currently to see my changes i need to restart server which takes time

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/less-loader#additionaldata

**Comment by ButuzGOL** [comment]
This helped me 
https://github.com/webpack-contrib/less-loader/issues/303#issuecomment-616686663
but anyway not so fast as with less variant
