### ISSUE TITLE
Less has finished and no sheets were loaded

### ISSUE THREAD

**Issue by jrmcdona** [webpack-contrib/less-loader#231]
Node: v8.9.1
Webpack: 3.6
"less": "^2.7.3",
"less-loader": "^4.0.5",

The issue I am having is that Webpack and Less-loader add the styles to the bottom of the <head> section.
Which means they load after my reference to Less's Less.js.   

Therefore the Less.js is outputting in the console:
**Less has finished and no sheets were loaded**

Anyone thoughts on how to change this behavior?

Thanks

**Comment by evilebottnawi** [comment]
Please update less-loader to latest version, if you still have problem please open new issue with reproducible test repo
