### ISSUE TITLE
display:flex Compatibility

### ISSUE THREAD

**Issue by Likunone** [webpack-contrib/less-loader#232]
![image](https://user-images.githubusercontent.com/15193414/33415646-cf990eb0-d5d2-11e7-907b-639fbef7a66b.png)

**It shouldn't be display:-webkit-flex?**

**Comment by michael-ciniawsky** [comment]
Nope Chrome fully supports [CSS Flexbox Layout Module Level 1](https://caniuse.com/#search=flexbox) for a while now, so the `-webkit` prefix isn't needed anymore
