### ISSUE TITLE
[docs] the `noIeCompat` option should be `ieCompat`

### ISSUE THREAD

**Issue by yume-chan** [webpack-contrib/less-loader#238]
At [README.md#73](https://github.com/webpack-contrib/less-loader/blob/9ed895fd8bbeb919e42b9137cdf0858a654b6275/README.md#73) it reads: `noIeCompat: true`. 

But the `noIeCompat` option is only understandable by the lessc command line tool, not the `less.render()` call, it should be `ieCompat`.

I can only find the full list of options in less source code:

https://github.com/less/less.js/blob/60a5c3bd1f6807615d017a5019031da47e1f480d/lib/less/contexts.js#L19-L33

https://github.com/less/less.js/blob/60a5c3bd1f6807615d017a5019031da47e1f480d/lib/less/contexts.js#L43-L53

Maybe there should be a note in the README for it.

**Comment by cap-Bernardito** [comment]
Thank you for your comment. Fixed
