### ISSUE TITLE
can't resolve webpack alias

### ISSUE THREAD

**Issue by dserWei** [webpack-contrib/less-loader#240]
I have the webpack config like this.
```
{
  context: path.resolve(__dirname, '../'),
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json', '.less', '.css'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '$': resolve('src'),
      '$components': resolve('src/components'),
      '$styles': resolve('src/styles'),
      '$element-theme.scss': path.resolve(__dirname, '..', 'src/assets/styles/element-theme.scss'),
      '$theme.less': path.resolve(__dirname, '..', 'src/assets/styles/theme.less')
    }
  }
...
```

But I got error when I import the module in some vue file like this.
```
<style lang="less">
  @import "~$theme";
  .nav {
    width: 100%;
    height: 60px;
```
<img width="1287" alt="2018-02-13 3 34 35" src="https://user-images.githubusercontent.com/7099525/36138236-8abf5f1a-10d3-11e8-83f7-7a2f20b294e8.png">

IMPORTANT: I got this error in version@4.0.5 but it works when I use 2.2.3
I find the difference is that loadercontext.resolve syntax transforms to be a promise. However it got into the reject function in my case.

**Comment by devrsi0n** [comment]
I have a similar situation here, only downgrading `less` to `'^2.7.3'` resolve the problem.

**Comment by cap-Bernardito** [comment]
You defined alias `$theme.less`, but use `$theme`. Try using the same aliases. I'm closing this.
If the problem recurs, please create minimum github reproducible test repository and reopen, or open a new issue.
