### ISSUE TITLE
Less Loader installation peer dependencies

### ISSUE THREAD

**Issue by Quadriphobs1** [webpack-contrib/less-loader#241]
I have installed `"less": "^3.0.1",` and also its in my `package.json` but each time i install `less-loader` i got the error that `less-loader@4.0.5 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.`

Now i dont undertstand what is the main issue here again. In my `package.json` i now have 

> "less": "^3.0.1",

> "less-loader": "^4.0.5",

**Comment by rejas** [comment]
Is it an error or just a warning? If the latter then you can probably ignore it until this library updates its dependencies.

**Comment by michael-ciniawsky** [comment]
It's a warning, but there are also bugs with `less > v3.0.0` as it seems atm. PR is here #242
