### ISSUE TITLE
`url` string with spaces gets unescaped

### ISSUE THREAD

**Issue by ilyapoz** [webpack-contrib/less-loader#247]
Here is the reproducer: https://github.com/ilyapoz/less-loader-repr/blob/master/dist/style.css (dist committed).
css loader alone works correctly, lessc too. 

Was unable to get tests to work in current master as it requires webpack 4, which currently has problems with text extract plugin at least. A newb to this :)

**Comment by evilebottnawi** [comment]
Can't understand problem, please update your deps, if you still have problem please open new issue with reproducible test repo, thanks
