### ISSUE TITLE
@Import could not resolve  '@import "./themes/default";'  which doesn't  have ".less" suffix   

### ISSUE THREAD

**Issue by RobinLJB** [webpack-contrib/less-loader#248]
I found that less-loader will automatically create a plugin named <code>WebpackFileManager</code> [https://github.com/webpack-contrib/less-loader/blob/master/src/createWebpackLessPlugin.js](url) 
  while less-loader doesn't have the <code>paths</code> options

but this plugin seem to could not resolve "@import" correctlly like  <code>@import "./themes/default";</code>  which doesn't  have ".less" suffix ;

Maybe because this plugin will validate the file name and the file name must be statisfied the rule that have a ".less" suffix.
  
<code>
          
         const isLessCompatible = /\.(le|c)ss$/;
           
          if (isLessCompatible.test(resolvedFilename)) {
            return readFile(resolvedFilename)
              .then(contents => contents.toString('utf8'));
          }

          return loadModule([stringifyLoader, resolvedFilename].join('!'))
            .then(JSON.parse); 
</code>

And I found that in the less project  

[https://github.com/less/less.js/blob/master/lib/less/environment/abstract-file-manager.js](url)
<code>
          
           abstractFileManager.prototype.tryAppendLessExtension = function(path) {
                 return this.tryAppendExtension(path, '.less');
           }

</code>  

there is method in the <code>abstractFileManager</code> will try to add a suffix append the file name.  Maybe it could be useful.

And I resolved this problem by adding  a <code>paths</code> options . and it will not create  <code>WebpackFileManager</code>  plugin .......

**Comment by cap-Bernardito** [comment]
Will be fixed in the next release
