### ISSUE TITLE
How to enable javascript (less option)

### ISSUE THREAD

**Issue by DominicTobias** [webpack-contrib/less-loader#249]
Hi, thanks for the loader.

I'm curious how it still works in developement if it's not using less loader:

```
// use style-loader in development
fallback: "style-loader"
```

But also how to enable javascript functions in less so functions like `unit()` work - http://lesscss.org/functions/

If I put:

```
loader: 'less-loader',
options: {
  javascriptEnabled: true,
},
```

That's only going to load for the non production build isn't it? Thanks

**Comment by evilebottnawi** [comment]
`javascriptEnabled` is deprecated so it is not recommend to use

**Comment by JoeWrights** [comment]
> `javascriptEnabled` is deprecated so it is not recommend to use

emm, so is there have any other way to replace it?
