### ISSUE TITLE
Importing remote urls broken with v4.1.0

### ISSUE THREAD

**Issue by rejas** [webpack-contrib/less-loader#250]
With less-loader v4.0.6 I could import remote fonts like this in my main.less file:

`@import url('https://fonts.googleapis.com/css?family=Nunito');`

With v4.1.0 I now only get this error when trying to build (using webpack v3.1..0):

```
Message:
    ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/less-loader/dist/cjs.js??ref--1-4!./src/css/main.less
Module build failed:

 */
@import url('https://fonts.googleapis.com/css?family=Nunito');
^
Can't resolve './https://fonts.googleapis.com/css?family=Nunito' in 'C:\Projekte\mine\homepage\src\css'
      in C:\Projekte\mine\homepage\src\css\main.less (line 6, column 0)
```

**Comment by rejas** [comment]
Closing this issue, rather seems to be a problem with updating less from v2 to v3.... Will investigate further and re-open if neccesary at all...

**Comment by csergiu** [comment]
This is still a problem.
