### ISSUE TITLE
Is there a way to import .less files into other .less files without compiling them to CSS first?

### ISSUE THREAD

**Issue by ryanscottaudio** [webpack-contrib/less-loader#266]
* Operating System: macOS 10.13.5
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.12.1
* less-loader Version: 4.1.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          {
             loader: 'style-loader',
          },
          {
             loader: 'css-loader',
          },
          {
             loader: 'less-loader',
          },
        ],
      },
   ],
};
```

### Expected Behavior

Importing a .less file into another .less file imports the .less file as it is.

### Actual Behavior

Importing a .less file into another .less file converts the .less file into raw CSS and then back into .less (thereby removing proper `calc` and other important things).

### How Do We Reproduce?

Import a .less file with `calc(~"100% - 5px")` into another .less file.

**Comment by GrzegorzKaczan** [comment]
+1 same problem here

**Comment by rejas** [comment]
I seem to have the same problem since less got updated to v3.5:

```
Unhandled rejection Error in plugin "webpack-stream"
Message:
    ./src/css/main.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


.h5 {
    font-family: @font-header, serif;
  ^
Cannot read property 'substring' of undefined
      in C:\Projekte\mine\veeck.de\src\css\elements\headlines.less (line 7, column 4)
    at runLoaders (C:\Projekte\mine\veeck.de\node_modules\webpack\lib\NormalModule.js:284:20)
    at C:\Projekte\mine\veeck.de\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Projekte\mine\veeck.de\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Projekte\mine\veeck.de\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
 @ ./src/js/main.js 19:0-26
```

When removing all occurences of `calc `calls in my less files like `height: calc(100% + 10px);` the compilation runs through without problems. The calc-calls dont have anything to do with h5 or any other part of the error stack so thats why I think it has something to do with the issue here.

**Comment by evilebottnawi** [comment]
use file-loader, it is return path to less file

**Comment by rejas** [comment]
thx for the quick replay, but I am not sure if I understand. where should I use file-loader?

**Comment by seaBubble** [comment]
I am also seeing this issue intermitently

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


Cannot read property 'substring' of undefined
      in undefined (line undefined, column undefined)

**Comment by evilebottnawi** [comment]
You can use `raw-loader` or `file-loader`, put this above `less-loader`
