### ISSUE TITLE
about dependencies 

### ISSUE THREAD

**Issue by houfeng0923** [webpack-contrib/less-loader#269]
This issue is for a:

- [x] **modification** request

i do not think i  need  add `less` package in my project 's package.json .
so, can less-loader  mv the  less dependence from devDependencies to  dependencies node ?

**Comment by evilebottnawi** [comment]
@houfeng0923 it is good practice use `peerDependencies` for third party libraries, but when they required to use in code, it is allow to use difference version `less` (2 or 3 and future). Also please don't remove section from issue template in future. Thanks!

**Comment by houfeng0923** [comment]
hi @evilebottnawi :
 i agree with `peerDependencies`,  but i think `less` need in `dependencies ` but not in `devDependencies`. 
i think [postcss-loader](https://github.com/postcss/postcss-loader/blob/master/package.json#L14) is good setting.

**Comment by aibaiejoy** [comment]
but i think less need in dependencies but not in devDependencies，否则安装了less-loader的webpack配置中，会报错，缺少less包。
