### ISSUE TITLE
hsl colors compile issue

### ISSUE THREAD

**Issue by iron66** [webpack-contrib/less-loader#271]
* Operating System: Linux Kubuntu 18.04
* Node Version: v7.10.1
* NPM Version: 4.2.0
* webpack Version: 4.20.2
* less-loader Version: 4.1.0

This issue is for a:

- [x] **bug**

### Code

```css
border: 1px solid hsl(0, 0%, 85%);
```

### Expected Behavior
```css
border: 1px solid hsl(0, 0%, 85%); // or #d9d9d9
```

### Actual Behavior

```css
border: 1px solid hsl(0, 0, 85%);
```

### How Do We Reproduce?

Try to compile style with hsl colors with `mode=production`
In `development` mode, it just broke everything

**Comment by evilebottnawi** [comment]
IT is just wrapper around `less`, we don't modify you code, problem on `less` side, you maybe you use broken css minifier
