### ISSUE TITLE
less-loader/dist/cjs.js' is not a loader (must have normal or pitch function)

### ISSUE THREAD

**Issue by manniL** [webpack-contrib/less-loader#273]
# Warning

The following issue description sucks 😦 I'm on it!

* Operating System: Ubuntu 18.04
* Node Version: LTS (10.13)
* NPM Version: Yarn 1.12.1
* webpack Version: 4.24.0
* less-loader Version: latest (4.1.0)

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

## Preamble

I'm developing a Nuxt.js module, so I guess a lot of things play into that error.
However, I'm using `sass-loader` with the same setup and don't see any problem.
Possible issue might be the `cjs.js`.

### Expected Behavior

Use `less-loader` without problems.

### Actual Behavior

An error is thrown: `Error: Module '/path/to/node_modules/less-loader/dist/cjs.js' is not a loader (must have normal or pitch function)`

### How Do We Reproduce?

No "easy way" to do that :/ Sorry!
I'm working on a reproduction repo so you can at least run the test and see the same error.

**Comment by evilebottnawi** [comment]
Feel free to investigate and send a PR

**Comment by manniL** [comment]
@evilebottnawi Error vanished after nuking node_modules and reinstalling less-loader and less a few time 🤷‍♂️
