### ISSUE TITLE
less-loader blocks less node_modules support

### ISSUE THREAD

**Issue by matthew-dean** [webpack-contrib/less-loader#276]
This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior

Less 3.x+ should be able to import from node_modules by default without `~`

### Actual Behavior

less-loader's resolver forces a `~` even though none is necessary and can't resolve Less code in node_modules without `~`, even though that should work in Less 3.x+

In fact, if you comment out...
```
install(lessInstance, pluginManager) {
      //pluginManager.addFileManager(new WebpackFileManager());
    },
```
...then Less imports any given library from node_modules. e.g.: 
```less
@import 'iview/src/styles/index.less';  //imports from NPM iview module
```

So the file manager is actually blocking NPM / Node support unnecessarily. (Although it probably provides other Webpack resolving support?)

**Comment by jhnns** [comment]
You can switch to Less' resolver by specifying [`paths`](https://github.com/webpack-contrib/less-loader#less-resolver). Even an empty array should work :grin:.

Using Webpack's resolver as default was a design mistake. Maybe I will do a breaking change someday.

**Comment by cap-Bernardito** [comment]
Will be fixed in the next release
