### ISSUE TITLE
less-loader cannot parse less of color function 

### ISSUE THREAD

**Issue by shencailiang** [webpack-contrib/less-loader#277]
ERROR in ./fesrc/styles/main.less (./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js??ref--6-2!./fesrc/styles/main.less)
Module build failed: 

    background-color: var(--color-legend-1);
    box-shadow: 0 0 1px 6px color(#f7f800 alpha(20%));
                                        ^
Error evaluating function `alpha`: color.toHSL is not a function

**Comment by evilebottnawi** [comment]
Because less doesn't support this
