### ISSUE TITLE
Unrecognised input: stroke property

### ISSUE THREAD

**Issue by DzmVasileusky** [webpack-contrib/less-loader#280]
* Operating System: MacOS Mojave 10.14
* Node Version: 8.11.4
* NPM Version: 6.5.0
* webpack Version: 4.19.1
* less-loader Version: 4.1.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

```
.axis path,
.axis line {
	fill: none;
	stroke: #f4f4f4;
	shape-rendering: crispEdges;
}
```

##### CLI Command

```bash
  # paste the CLI command you're using. if this isn't applicable, it's safe to remove.
  $ {ng serve}
```

### Expected Behavior

File is compiled

### Actual Behavior

File isn't compiled

> ERROR in ./src/less/styles.less (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/less-loader/dist/cjs.js??ref--17-3!./src/less/styles.less)
> Module build failed (from ./node_modules/less-loader/dist/cjs.js):
> 
> .axis path {
> 	stroke: #ссс;
>        ^
> Unrecognised input
>       in /Users/.../src/less/common/graphs.less (line 4, column 4)

**Comment by DzmVasileusky** [comment]
This is strange. But this code is working if I place it in another file.

@import "common/fonts"; // works inside this file
@import "common/graphs"; // doesn't work here

**Comment by evilebottnawi** [comment]
Looks something invalid in configuration, please create reproducible test repo

**Comment by DzmVasileusky** [comment]
I have solved an issue. Don't know why but retyping color value for stroke fixed it.
