### ISSUE TITLE
Add support for file-loader 3.x

### ISSUE THREAD

**Issue by hpohlmeyer** [webpack-contrib/less-loader#282]
* Operating System: MacOS 10.14.2
* Node Version: 11.4.0
* NPM Version: 6.4.1
* webpack Version: 4.28.1
* less-loader Version: 4.1.0

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Code

[Webpack config](https://gist.github.com/hpohlmeyer/2e357a3bbdf955267cddb25c1d86a7e9)

The styles.less file, that throws the error:
```less
@import './fonts';

/** Import CSS for custom components, that are not part of the ui library. */
@import './custom/code-block';
@import './custom/http-operation-badge';
```

### Expected Behavior
Should compile without errors.

### Actual Behavior
Breaks with 

```
ERROR in ./src/styles/styles.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./src/styles/styles.less)
Module not found: Error: Can't resolve 'url-loader' in '/absolute/path/to/project'
```

I suppose this is caused by [the removal of `file-loaders` `useRelativePath`-option in version 3.0.0](https://github.com/webpack-contrib/file-loader/releases/tag/v3.0.0).

@jhnns said that [the less-loader usually applies the `relativePath`-option automatically](https://github.com/webpack-contrib/less-loader/issues/76#issuecomment-201487970), which sound like a problem, if the option is not supported anymore.

### How Do We Reproduce?

Use less-loader with file-loader 3.x

**Comment by evilebottnawi** [comment]
Not related to `less-loader`, you need install `url-loader`
