### ISSUE TITLE
Module build failed (from ./node_modules/less-loader/dist/cjs.js)

### ISSUE THREAD

**Issue by EricAdonis** [webpack-contrib/less-loader#292]
- Operating System: OSX
- Node Version: v10.15.2
- YARN Version: 1.16.0
- Webpack Version: 4.31.0
- less-loader Version: 4.1.0
- less Version: 2.7.3

### Issue
After run webpack-dev-server then result on terminal is not error.
<img width="1680" alt="Screen Shot 2019-05-20 at 12 01 25 AM" src="https://user-images.githubusercontent.com/49099200/57985451-7055dd00-7a92-11e9-8f33-26ecb813ca50.png">
But changed file and HRM reload, then i get result is.
<img width="1680" alt="Screen Shot 2019-05-20 at 12 02 18 AM" src="https://user-images.githubusercontent.com/49099200/57985473-bb6ff000-7a92-11e9-91a1-9e1ebe7582a2.png">

- This is my repo: https://github.com/EricAdonis/innos-ui-ts
- Can't you help me ?

**Comment by evilebottnawi** [comment]
@EricAdonis problem still exists?

**Comment by EricAdonis** [comment]
> @EricAdonis problem still exists?

Not, it work. #9485
