### ISSUE TITLE
Importing less files does not use webpacks splitchunk optimization

### ISSUE THREAD

**Issue by chickenwing** [webpack-contrib/less-loader#293]
When importing the same less file into two less files, it should create a shared chunk based on webpacks splitchunk optimization.
It currently only works when importing the less files in js files.
When importing inside less files, it creates duplicate css.

webpack config:

	optimization: {
		splitChunks: {
			chunks: "all"
		}
	}

A related problem seems to exists with the sass-loader: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/49

* Operating System: linux
* Node Version: v8.16.0
* NPM Version: 3.10.3
* webpack Version: 4.28.4
* less-loader Version: 5.0.0

**Comment by evilebottnawi** [comment]
No, you should manually setup `splitChunks`, by default `splitChunks` works only for js
