### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by elios264** [webpack-contrib/less-loader#296]
* Operating System: Mac
* Node Version: 12.4
* NPM Version: 6.10
* webpack Version: 4.35.2
* less-loader Version: 5.0.0

### Expected Behavior

Compile without problems
### Actual Behavior
Magic error that disappears when recompiling:

### Code

```

  Webpack compilation failed (client)

    ERROR in ./theme/theme.client.less
    Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ../node_modules/less-loader/dist/cjs.js):


    Cannot read property 'substring' of undefined
          in undefined (line undefined, column undefined)
        at /Users/elios264/Desktop/alto/promo-panel/node_modules/webpack/lib/NormalModule.js:302:20
        at /Users/elios264/Desktop/alto/promo-panel/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /Users/elios264/Desktop/alto/promo-panel/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at context.callback (/Users/elios264/Desktop/alto/promo-panel/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
     @ ./client/appLoader.js 10:0-33
     @ multi webpack-hot-middleware/client?dynamicPublicPath=true react-hot-loader/patch ./client/appLoader
```

```
    ERROR in ./src/theme/theme.client.less (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--5-3!./src/theme/theme.client.less)
    Module build failed (from ../node_modules/less-loader/dist/cjs.js):
    
    
    Cannot read property 'substring' of undefined
          in undefined (line undefined, column undefined)
```

### How Do We Reproduce?

* Clone: https://github.com/elios264/less-loader-bug
* npm install
* npm start

it happens half the time, probably a race condition because, if I save any file (so webpack recompiles), it will recompile fine, in a larger project I have happens everytime and I have to force webpack to recompile

related:
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/421

**Comment by jasonverber** [comment]
+1, this has been the bane of my existence the past two or three weeks. Very intermittent, but unfortunately it always seems to rear its head during automated build tests (less often during local development.)

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by jasonverber** [comment]
Disabling sourcemaps seems to avoid this altogether.

**Comment by jasonverber** [comment]
I believe this is actually an issue with less itself: https://github.com/less/less.js/pull/3360

**Comment by evilebottnawi** [comment]
Thanks for link

**Comment by cap-Bernardito** [comment]
Please upgrade `less` package to the latest version.

**Comment by saddampojee** [comment]
Thanks. Upgrading `less` package to the latest version solves the problem.

**Comment by ronmi-tr** [comment]
hi
 am working in a big project with a many developers
and i am the only one getting this  error

ERROR in Module build failed (from ./node_modules/less-loader/dist/cjs.js):


Cannot read property 'substring' of undefined
      in undefined (line undefined, column undefined)
i updated to latest less loader version and i got some new errors

**Comment by alexander-akait** [comment]
@ronmi-tr please create reproducible test repo
