### ISSUE TITLE
Incorrectly interpreting root paths as relative

### ISSUE THREAD

**Issue by andrewplummer** [webpack-contrib/less-loader#298]
* Operating System: OSX
* Node Version: 10.16.0
* Yarn Version: 1.16.0
* webpack Version: 4.28.1
* less-loader Version: 5.0.0

Similar to `babel-loader`, I would expect to be able to import files from the root path, i.e.:

```less
@import 'src/styles.less';
```

This doesn't seem to work with less-loader which converts all non-relative paths that do not begin with `~` to relative.

### Expected Behavior

Should be able to import files relative to root.

### Actual Behavior

Files are interpreted as relative.

**Comment by evilebottnawi** [comment]
`@import 'src/styles.less';` means `@import './src/styles.less';`, sorry I can't reproduce locally, if you still have a problem please open a new issue with reproducible test repo, thanks

**Comment by andrewplummer** [comment]
I'm not sure what you mean by "cannot reproduce". The behavior you described above is contradictory to babel and ES6 imports, no?

**Comment by evilebottnawi** [comment]
@andrewplummer because less/sass/css is not module language, so using `src/styles.less` means load `style.less` from `src` directory

**Comment by andrewplummer** [comment]
Of course they are... sass and less both have `@import` statements to import locally scoped styling modules, complete with scripting functionality. Whatever underlying semantic difference that might have with JS modules, why would you expect them to function any differently, especially when they are so commonly used together?

**Comment by evilebottnawi** [comment]
What is a problem? I can't understand you, what do you expected using `@import 'src/styles.less';`? What file should be loaded?

**Comment by andrewplummer** [comment]
Apologies it's been a while since I opened this and I didn't remember the details, also I don't think I explained it properly. The issue is that `less-loader` isn't respecting webpack's `resolve` parameter. Here is the relevant code:

```js
// webpack.config.js
const path = require('path');
module.exports = {
  resolve: {
    modules: [path.join(__dirname, 'src'), 'node_modules']
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.(css|less)$/,
        use: [
          'less-loader'
        ]
      },
    ]
  },
};

```

```js
// src/index.js
import 'public/foo.less';
import 'public/foo';
```

```js
// src/public/foo.js
import './bar'; // Relative import works
import 'public/bar'; // Also works as it respects resolve.modules in webpack.config.js
```

```less
// src/public/foo.less
@import './bar';      // Relative import works;
@import 'public/bar'; // Fails as it doesn't respect webpack.config.js
```

**Comment by evilebottnawi** [comment]
Oh, thanks for clarify, we are already fixed it in master :+1:

**Comment by andrewplummer** [comment]
oh, excellent thank you!
Is there a way I can test it?

**Comment by andrewplummer** [comment]
Nevermind just built master and ran, works great! thanks so much
