### ISSUE TITLE
Duplicate selectors when use `each` loop syntax

### ISSUE THREAD

**Issue by alireza-mh** [webpack-contrib/less-loader#299]
* Operating System: MacOS 10.14.5
* Node Version:  11.4.0
* NPM Version: 6.9.0
* webpack Version: 4.20.2
* less-loader Version: 5.0.0

### Expected Behavior

when we create selectors with `each` keywords, for example, in the `main` file if we import `main` file with reference keyword our output should not have duplicate selectors.

### Actual Behavior
these kinds of selectors will be duplicated on the output file
### Code

 ```js
each(range(1, 5), {
  .flex-@{value} {
    flex: @value
  }
})
```

### How Do We Reproduce?
copy and paste flex generator code in one file and import it with reference in other less files.

there is a workaround for those who faced the same issue, you can put all generated selectors in one file and import it once in your js file.

**Comment by fewspider** [comment]
some here

**Comment by evilebottnawi** [comment]
We don't modify you input, because less works like that

**Comment by alireza-mh** [comment]
strange, it seems it is expected behavior according to this `less` issue: 
https://github.com/less/less.js/issues/3402

**Comment by evilebottnawi** [comment]
Yes, we can't do something on our side, maybe cssnano allow to you remove unnecessary selectors
