### ISSUE TITLE
Fixed: Issue after upgrading to CRA 3.1.1

### ISSUE THREAD

**Issue by leojh** [webpack-contrib/less-loader#304]
* Operating System: macOS Mojave
* Node Version: 11.1.0
* NPM Version: 6.10.3
* webpack Version: 4.3.2
* less-loader Version: 5.0.0

Not sure if this belongs here but hoping to help the next person that stumbles into this issue. Recently, we upgraded to `create-react-app` version `3.1.1` which added the following section to `webpack.config.js`

```
{
          loader: require.resolve('resolve-url-loader'),
          options: {
            sourceMap: isEnvProduction && shouldUseSourceMap,
          },
        },
```

this broke the relative file references inside of our `less` files like `url(...)` for example. However, adding `absolute: true` fixed the issue.

```
{
          loader: require.resolve('resolve-url-loader'),
          options: {
            sourceMap: isEnvProduction && shouldUseSourceMap,
            absolute: true
          },
        },
```

**Comment by evilebottnawi** [comment]
Don't use `resolve-url-loader` for `less-loader` because `less-loader` able to handle url, you don't need this loader

**Comment by leojh** [comment]
@evilebottnawi thank you. `resolve-url-loader` comes with CRA now. not sure what other side-effects could happen there if it's removed.

**Comment by evilebottnawi** [comment]
Maybe you should open issue in `resolve-url-loader`
