### ISSUE TITLE
Can not split common module in the less file

### ISSUE THREAD

**Issue by 100001** [webpack-contrib/less-loader#306]
* Operating System: OSX 10.14.6 
* Node Version: v10.13.0
* NPM Version: 6.4.1
* webpack Version: 4.41.0
* less-loader Version: 5.0.0

I have an _a.less_ and a _b.less_, which together reference the _c.less_, like the following:

a.less:
```js
//a.less
@import './c.less'
...
```
b.less:
```js
//b.less
@import './c.less'
...
```
webpack.config.js:
```js
... {
entry: {
        a: './A.js',// require('./a.less')
        b: './B.js'// require('./b.less')
    },
   ...
    mode: 'production',
    module: {
        rules: [ {
            test: /\.less$/,
            use: [
                MiniCssExtractPlugin.loader,
                'css-loader',
                'less-loader'
                ]
        }]
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: 'css/[name].css',
        }) 
    ],
    optimization: {
        splitChunks: {
            minChunks: 2,
            maxInitialRequests: 5,
            minSize: 0,
            cacheGroups: {
                common: {
                    chunks: "all"
                }
            }
        },
        runtimeChunk: {
            name: 'manifest'
        }
    }
}
```
Following are the build results:
_css/a.css_
_css/b.css_

But if only use css-loader with the css files, the results will like this:
_css/a.css_
_css/b.css_
_css/common\~a\~b.css_

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by 100001** [comment]
> Please create minimum reproducible test repo

https://github.com/100001/less-loader-test     please clone the example,  thanks

**Comment by 100001** [comment]
@evilebottnawi  https://github.com/100001/less-loader-test please clone the example, thanks

**Comment by evilebottnawi** [comment]
Sorry, not related to less-loader, if you still have a problem please open a new issue in `MiniCssExtractPlugin`
