### ISSUE TITLE
Next Version roadmap

### ISSUE THREAD

**Issue by anikethsaha** [webpack-contrib/less-loader#307]
## This issue is regarding the next version of less-loader.

As far as the changelog for [less@3.10.0beta](https://github.com/less/less.js/blob/master/CHANGELOG.md#3100-beta) is concerned and release of less-loader@5, I couldn't see any major feature addition to the project.
So what I would suggest that this loader can fill some of the missing features of the less in general.
Looking at the issues, I tried to list a couple of issues which can be good to have it in the loader

**Update**
This issue is working with webpack running in watch mode

### 1. Image importing (Bug)

Issue: https://github.com/webpack-contrib/less-loader/issues/234
This is supported by `less` in general but couldn't able to achieve the same using less-loader.
It can be implemented by resolving the `need an appropriate loader for .png` issue when importing. I guess this is blocking the remaining execution of the less-loader and stopping the webpack compilations

### 2. Dependencies update

Adding support for node 10x and updating required dependencies

---

These are what I think would be good to add for the next release.
Please add if anything is missing.
cc @evilebottnawi

---

#### Not required

- remote importing (Not required)
  Issue: https://github.com/webpack-contrib/less-loader/issues/95
  What I can suggest for this is making and adding a plugin for. Handling this in the core will be quite tweak.
  The plugin will make a request to the file and download the content of it and placing those in a temporary file that will not be in the project structure.
  This might affect the caching and there can be few things to resolve like when to delete the temporary file and when to keep it

Update:
---
### 1. Re-compiling when @import file changes in watch mode (it is working as intended 👍 )

Issue: https://github.com/webpack-contrib/less-loader/issues/252
Although I didn't cross-check this when using with other loaders like style-loader. I guess it would be nice to have it on the roadmap

**Comment by evilebottnawi** [comment]
Thanks for issue. My ideas:

> 1. remote importing

It is supported less by default? 

> 2. Re-compiling when @import file changes in watch mode

Webpack has api for this, for example `sass` output what files were includes https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L111

If less does not do it, we should collect them in `Set`/`Array` and do same what do `sass-loader`, it should be easy

> 3. Image importing

hm, strange, should be work, i think it is invalid url in generated css from less, also we change logic in css-loader so this example should be work theoretically right now

---

I think we also should update deps and drop old node version (support only `10.13`)

**Comment by anikethsaha** [comment]
> It is supported less by default?

No, I guess, but I was thinking it can be good to have, but not necessary thats why I suggested a plugin to test it out.

> If less does not do it, we should collect them in Set/Array and do same what do sass-loader, it should be easy

So can this be considered for the roadmap?

> hm, strange, should be work, I think it is invalid URL in generated CSS from less, also we change the logic in CSS-loader so this example should be work theoretically right now

Yup, thats what poking me, it should work as less supports this but it's not working as when webpack is getting `.png` or `.jpg` etc, as the import, its throwing error for the need of an appropriate loader 


>  drop old node version (support only 10.13)

from 10.13x? will it be accessible to certain users, I guess many node users might be using 7+ or 8+ but making it 10.13+ may reduce the users count at the high peak I guess. 

Yeah, but updating the dep should be done soon I guess.

---

**Comment by evilebottnawi** [comment]
> No, I guess, but I was thinking it can be good to have, but not necessary thats why I suggested a plugin to test it out.

If no, we should don't handle this urls, it is out of scope of loader

> So can this be considered for the roadmap?

Yes

> Yup, thats what poking me, it should work as less supports this but it's not working as when webpack is getting .png or .jpg etc, as the import, its throwing error for the need of an appropriate loader

We need investigate this, it is strange, feel free to investigate this and send a fix

> from 10.13x? will it be accessible to certain users, I guess many node users might be using 7+ or 8+ but making it 10.13+ may reduce the users count at the high peak I guess.

node@8 is deprecated at the end of the year, do not support older versions

> Does Less-loader support all the flags provided by the less(-CLI) ?

We should support only `less` node API options

Anyway feel free to send a PR with new fix/features

**Comment by anikethsaha** [comment]
Sure, I guess I will start with the updating of the dependencies as it won't break things later after doing the other features

**Comment by evilebottnawi** [comment]
Feel free to ping me if you need help with something

**Comment by anikethsaha** [comment]
Recompiling in watch mode is working fine as intended 👍

**Comment by evilebottnawi** [comment]
Most of issue solved, problem with https://github.com/webpack-contrib/less-loader/issues/234 will be solved in the issue
