### ISSUE TITLE
Poor readme document.

### ISSUE THREAD

**Issue by jzfed** [webpack-contrib/less-loader#309]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
This document is badly written. Can you write a good example that works well? Instead of picking up a few code snippets and letting the first time users waste time to solve various unmentioned problems.

### Your Proposal for Changes

**Comment by evilebottnawi** [comment]
What is bad?

**Comment by rockneverdies55** [comment]
What is bad?

I'm copy pasting your snippet from readme:
```
        {
          test: /\.less$/,
          use: [
            {
              loader: 'style-loader', // creates style nodes from JS strings
            },
            {
              loader: 'css-loader', // translates CSS into CommonJS
            },
            {
              loader: 'less-loader', // compiles Less to CSS
            },
          ],
        },
```
Then in my component:
`import '../assets/styles/main.less';`

And when I run the build, I get:

`
(function (exports, require, module, __filename, __dirname) { @import ~normalize.css/normalize.css';   
SyntaxError: Invalid or unexpected token
`

This is bad. Even the basic setup doesn't work with this readme.

**Comment by evilebottnawi** [comment]
@rockneverdies55 please create reproducible test repo

**Comment by rockneverdies55** [comment]
Hey @evilebottnawi, sorry about that. After spending hours and hours struggling on this, I was finally able to figure out that the issue was originated from server side rendering. Sorry again I thought it was about this plugin's setup.

**Comment by evilebottnawi** [comment]
If somebody have ideas how we can improve docs feel free to send a PR
