### ISSUE TITLE
Less-loader 5.0.0: Not working with Vue-Cli 4.2.0

### ISSUE THREAD

**Issue by gavinwyf** [webpack-contrib/less-loader#329]
- Operating System:  MacOS 10.15.3 
- Node Version: v13.0.1
- NPM Version: 6.12.0
- webpack Version: 4.42.0
- less-loader Version: 5.0.0

### What is actually happening?

This is not working using version 5.0.0:

```js
// vue.config.js
    css: {
        loaderOptions: {
            less: {
                paths: [path.resolve(__dirname, 'src/assets/styles/variables.less')],
                prependData: loaderContext => {
                    const { resourcePath, rootContext } = loaderContext;
                    const relativePath = path.relative(rootContext, resourcePath);
                    return '@import "~@/assets/styles/variables.less";';
                },
                prependData: `@import "~@/assets/styles/variables.less";`,
                data: '@import "~@/assets/styles/variables.less";',
            },
        },
    },
```
I tried a lot of things,  none of which worked. 
Using the loader options, I didn't have much luck.
prependData, data, paths all of them not worked. Only globalVars worked but can`t import all the less file.

**Comment by cap-Bernardito** [comment]
The option `prependData` is not yet available because there has not yet been a release. The release will be soon.

**Comment by truefusion** [comment]
For some reason, Vue CLI is still installing v5 of less-loader. Upgrading to the latest less-loader does fix the issue.
