### ISSUE TITLE
Loader doesn't import optional files with include paths

### ISSUE THREAD

**Issue by jsarem** [webpack-contrib/less-loader#338]
- Operating System: Windows 10 [1909]
- Node Version: v10.19.0
- NPM Version: 6.13.4
- webpack Version: 4.42.1
- less-loader Version: 5.0.0

### Expected Behavior

Less loader with `lessOptions.paths` option doesn't use find optional files in the parent folder. Same setup works with plain `lessc` compiler.

### Actual Behavior

Less loader should import all files with custom paths.

### Code

```js
{
  loader: 'less-loader',
  options: {
    lessOptions: {
      paths: [
        path.resolve(__dirname, '../'), // <-- Use parent folder as one of the paths
      ],
    }
  }
}
```

```less
// Works fine
import './app.less';

// Doesn't work
// Real file path: "../custom/override.less"
import (optional) 'custom/override.less';
```

See the repo for detailed version

### How Do We Reproduce?

See: https://github.com/jsarem/webpack-less-loader-include-paths

In the test repo there are two commands: `yarn build-webpack` and `yarn build-lessc`. Latter creates right output css file.

**Comment by cap-Bernardito** [comment]
Fixed in master, release will be soon.
