### ISSUE TITLE
less should be a peer dependency

### ISSUE THREAD

**Issue by rjgotten** [webpack-contrib/less-loader#352]
`less` is currently registered as a `dependency` when it should be a `peerDependency`:

https://github.com/webpack-contrib/less-loader/blob/73740a89aef0748e27657a06b80b327c90b6f2b4/package.json#L45

Locking it as a dependency means users are not free to pick their own minimum version even though `less-loader` is API-compatible.

This right now creates a big problem for users that process any non-trivially sized stylesheet collection, as Less versions 3.10+ have [hugely increased memory consumption](https://github.com/less/less.js/issues/3434) after the codebase was converted to ES classes and is now being transpiled (first with Babel, now with TypeScript) down to ES5.

Seeing 500+ MB memory usage for compiling a single stylesheet is not out of the ordinary.

**Comment by evilebottnawi** [comment]
Sorry, we can't put it in `peerDependency`, because we provide `less` out of box, I will reduce required less version, if you use `yarn` you can use https://classic.yarnpkg.com/en/docs/selective-version-resolutions/, it is acceptable?

**Comment by rjgotten** [comment]
No, it is not acceptable. less should not be provided out of the box.
Good loader design mandates that you use a peer dependency if you are simply wrapping another package and providing interface glue-code (which is what less-loader does).

https://webpack.js.org/contribute/writing-a-loader/#peer-dependencies

**Comment by evilebottnawi** [comment]
@rjgotten Okay, I can implement the `implementation` option:
```
{
  loader: 'less-loader'
  options: {
    implementation: require.resolve('less')
  }
}
```

We want to improve 0CJS and reduce complex of configuraions.

**Comment by rjgotten** [comment]
That's actually even more flexible. :+1:
Would allow mocking the entire compiler, in essence.

**Comment by evilebottnawi** [comment]
Yep, in my TODO
