### ISSUE TITLE
Restriction field breaks builds

### ISSUE THREAD

**Issue by SergeyPanchenkoWeWork** [webpack-contrib/less-loader#366]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- less-loader Version:
6.1.2

### Expected Behavior

The introduced PR https://github.com/webpack-contrib/less-loader/pull/362 which tagged without breaking change that was released in Patch version 6.1.2 breaks popular libraries such as https://github.com/Semantic-Org/Semantic-UI that uses not standard file extensions such as `.config`, `.variables` and `.overrides` 

### Actual Behavior

Webpack build is failing when trying to import file with `.overrides` / `.variables`  /  `.config` extensions 

### How Do We Reproduce?

Here is a repo CRA + Semantic-ui, I wanted to create a real life example with popular libraries
https://github.com/SergeyPanchenkoWeWork/semantic-sample-app

You can see the error running master branch with version 6.1.2
https://app.circleci.com/pipelines/github/SergeyPanchenkoWeWork/semantic-sample-app/3/workflows/29b55218-e539-4983-97ee-c89aa928e1fa/jobs/3

Here is same app running version 6.1.1
https://app.circleci.com/pipelines/github/SergeyPanchenkoWeWork/semantic-sample-app/4/workflows/eb9ec2dc-3329-4997-ac72-59de4d426631

It tries to load `.config` file and fails, and this file is what semantic-ui depends upon.

**Comment by evilebottnawi** [comment]
@SergeyPanchenkoWeWork Please provide minimum reproducible test repo, original source code uses `.less` files

**Comment by evilebottnawi** [comment]
Sorry, you ignore "How Do We Reproduce?" step, so we can't help, every day we get a lot of reports, so we cannot waste time guessing and trying to find something and somewhere, so please fill the issue template and we will reopen it and fix it.

**Comment by evilebottnawi** [comment]
@cruzdanilo :-1: ? You can create minimum reproducible test repo, instead the negative reaction, I can't fix problem that can't be reproduced, sorry

**Comment by cruzdanilo** [comment]
@evilebottnawi why close it? other users can collaborate on the same issue

**Comment by SergeyPanchenkoWeWork** [comment]
@evilebottnawi Added reproducible repo that shows the bug to ticket description. could you please reopen the issue?

**Comment by CoericK** [comment]
happening to me as well using react-semantic-ui, had to downgrade to v6.1.1
