### ISSUE TITLE
Build fail when mixing SCSS and LESS since 6+ upgrade

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/less-loader#368]
Hi webpack team!

I am having an issue when trying to **mix sass and less code together using webpack**. Everything was working fine until I upgrade my configuration to `less-loader@6+`.

I have tried to reduce/simplify as more as possible my webpack/build workflow, giving you only the part that fail in the buid.

- Operating System: Win7 x64
- Node Version: 13.12.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- less-loader Version: 6.1.3

### Expected Behavior

Build success.
It should output `dist/app.css` file.

### Actual Behavior

Build failure.

### Code

```js
// webpack.config.js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = () => ({
  mode: 'development',
  entry: [
    './build.less'
  ],
  module: {
    rules: [{
      test: /\.(le|c)ss$/,
      use: [MiniCssExtractPlugin.loader, 'css-loader', 'less-loader']
    }, {
      test: /\.scss$/,
      use: ['sass-loader']
    }]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'app.css'
    })
  ]
});
```

```scss
// vendor.scss -> only contain SCSS code
@import '~foundation-sites/scss/foundation.scss';
@include foundation-global-styles;
```

```less
// build.less -> can contain SCSS and LESS import/code
@import 'vendor.scss';

@color: 'blue';

.h1 {
  color: @color;
}
```

### How Do We Reproduce?
1. create the appropriate files (with given content)
- `webpack.config.js`
- `vendor.scss`
- `build.less`

2. install dependencies
```sh
npm i -D css-loader less-loader mini-css-extract-plugin node-sass sass-loader webpack webpack-cli foundation-sites
```

3. run `npx webpack`

### Additional notes
This was working fine with the previous version, using:
- `less@3.11.3`
- `less-loader@5.0.0`

So you can make the build success with:
```sh
npm i -D less@latest less-loader@5.0.0
npx webpack
```

Thanks for your feedback! :wink:

**Comment by evilebottnawi** [comment]
It is deprecated and was removed due perf and compatibility problems, you need refactor your structure and using `sass-loader` for `sass`/`scss` and `less-loader` for `less` and don't mix them

**Comment by evilebottnawi** [comment]
Just put in your JS file:
```
import 'styles.scss';
import 'styles.less';
```

**Comment by evilebottnawi** [comment]
Or:
```
entry: [
    './styles.scss',
    './styles.less'
],
```

**Comment by xavierfoucrier** [comment]
Hi @evilebottnawi,

Thanks for the clarification.
I will refactor as you suggest :wink: 

As usual, thanks for the fast answer!
