### ISSUE TITLE
Runtime variable modifications

### ISSUE THREAD

**Issue by itayganor** [webpack-contrib/less-loader#373]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

#### Some background

In my app, I'm trying to implement multiple themes.

I use Less with CSS Modules, and every `.module.less` file begins with `@import '../../path/to/theme.less`.

The structure is as simple as:
```js
src/
    components/
        // whatever
    style/
        themes/
            light.less
            dark.less
        theme.less
```

##### style/theme.less
```less
@import './themes/light.less';
```

This file contains the default app theme, and the theme files (`light.less` and `dark.less`) are just files with the same theme variables with different values.

When trying to create a manual toggle between switches, it makes sense to use `less.modifyVars`. I tried to setup something as simple as:

```jsx
<button onClick={async () => {
    await less.modifyVars({'body-background-color': 'red', 'text-color': 'blue'});
    less.refreshStyles();
}}>
    Do something!
</button>
```

But this code only outputs `Less has finished and no sheets were loaded.` without any actual change.

### Your Proposal for Changes

Include some documentation on runtime variable modifications. It can be done through `less.modifyVars` or maybe some configuration in `webpack.config.js`. It's a common issue I see online, which doesn't have any actual solution.

Thanks!

**Comment by evilebottnawi** [comment]
Sorry it is out of scope less-loader, you need two/three loaders for this case, don't expose nothing in your bundle, so you can change it using js

**Comment by itayganor** [comment]
> Sorry it is out of scope less-loader, you need two/three loaders for this case, we don't expose nothing in your bundle from `less`, (it is increase size of bundle and decrease perf), so you can change it using js

Is this documented somewhere? what are those "two/three loaders" you mentioned?

**Comment by evilebottnawi** [comment]
You need write own loader for this, we just compile Less -> CSS and nothing more
