### ISSUE TITLE
Maybe we still need implementation option

### ISSUE THREAD

**Issue by otakustay** [webpack-contrib/less-loader#380]
- Operating System: macOS 10.15.6
- Node Version: v14.7.0
- NPM Version: yarn 1.22.4
- webpack Version: 4.x
- less-loader Version: 7.0.0

### Feature Proposal

We'd like to see `implementation` option in some cases.

### Feature Use Case

We are encapsulating webpack configurations into a custom npm package (say `custom-webpack`), inside it we introduces `less-loader` and others, however since `less-loader` requires `less` as a peerDependency, installing `less` in `custom-webpack` may cause incorrect less version when `custom-webpack` is used by another project.

Once a project using `custom-webpack` installs an incorrect version of `less` itself, and `less-loader` is by chance hoisted outside `node_modules/custom-webpack/node_modules`, it will resolve `less` to that wrong version but not the one installed by `custom-webpack` (which is located at `node_modules/custom-webpack/node_mocules/less`), this directory structure could be like this:

```
/
  /node_modules
    /less <-- wrong version
    /less-loader
  /custom-webpack
    /node_modules
      /less <-- correct version
```

To get rid of this issue, it's better to still have an `implementation` option, `custom-webpack` can define this options by passing a correct version of less instance.

**Comment by evilebottnawi** [comment]
Sorry, no, you should not do this, because it is bad idea to block updating dependencies for developers

> Once a project using custom-webpack installs an incorrect version of less itself, and less-loader is by chance hoisted outside node_modules/custom-webpack/node_modules, it will resolve less to that wrong version but not the one installed by custom-webpack (which is located at node_modules/custom-webpack/node_mocules/less), this directory structure could be like this:

You should put `less` to `devDependencies` in your project
