### ISSUE TITLE
less-loader resolve the wrong source

### ISSUE THREAD

**Issue by gogoyqj** [webpack-contrib/less-loader#385]
i'm using with bit, project's structure is:

```
boilerplate
├── components/home/sfc-avatar
|  ├── SFCAvatar.less
|  └── node_modules/src/styles/mixins/index.less
└── src/styles/mixins.less
```

and the SFCAvatar.less:

```less
@import 'src/styles/mixins';
```

the less-loader config

```js
{
  test: /\.less$/,
  use: [
    'style-loader',
    'css-loader',
    {
      loader: 'less-loader',
      options: {
        lessOptions: loaderContext => {
          const { context, rootContext } = loaderContext;
          return {
            paths: [
              path.join(context, 'node_modules'),
              path.join(process.cwd(), 'node_modules'),
              process.cwd()
            ]
          };
        }
      }
    }
  ]
}
```

- Operating System: Mac
- Node Version: 10
- NPM Version: 6.4.1
- webpack Version: 4.28.4
- less-loader Version: 7.0.1

### Expected Behavior

SFCAvatar.less should import the `node_modules/src/styles/mixins/index.less`

### Actual Behavior

 `src/styles/mixins.less` imported

**Comment by gogoyqj** [comment]
it should work just like sass-loader when `SASS_PATH=node_modules:src` specified

**Comment by ryanclark** [comment]
Can you provide a small reproducible example please? I'll clone it locally and take a look

**Comment by gogoyqj** [comment]
@ryanclark here is the demo https://github.com/gogoyqj/less-loader-demo

![image](https://user-images.githubusercontent.com/1776278/94422983-7c8b9780-01ba-11eb-919f-ad4cbeceaa5c.png)

**Comment by cap-Bernardito** [comment]
In `less-loader`, the native `less` resolver is executed first, which returns this result.
Less resolver tries to look for the following files:
- `(cwd) /components/home/sfc-avatar/src/styles/mixins.less` (error, not found)
- `(cwd) /components/home/sfc-avatar/node_modules/src/styles/mixins.less` (error, not found)
- `(cwd) /node_modules/src/styles/mixins.less` (error, not found)
- `(cwd) /src/styles/mixins.less` (find, resolving complete)

You need file `(pwd) / src / styles / mixins.less` move to `(pwd) /src/styles/mixins/index.less`
Or when importing, specify explicitly the import `... / mixins.index`

**Comment by gogoyqj** [comment]
thank u

that's seems really a bit related problem：

sass：
![image](https://user-images.githubusercontent.com/1776278/94504047-750bd300-023a-11eb-9765-6e0394805ea1.png)

less：
![image](https://user-images.githubusercontent.com/1776278/94504085-8e148400-023a-11eb-94c4-52fcdf7136a8.png)

**Comment by evilebottnawi** [comment]
@gogoyqj sass !== less, they use different algorithm for resolving, resolved values was from less, so we can't fix it on our side

**Comment by gogoyqj** [comment]
@evilebottnawi thank u, i'll try to fix it by bit or less side
