### ISSUE TITLE
Non-less imports are not compiled using loaders defined in configuration

### ISSUE THREAD

**Issue by Rall3n** [webpack-contrib/less-loader#389]
- Operating System: Windows 10
- Node Version: 12.13.1
- NPM Version: 6.14.5
- webpack Version: 5.0.0
- less-loader Version: 7.0.2

### Expected Behavior

Non-less imports should import through the `webpack` loader chain to be converted into `less` compatible content.

This behavior is to be expected based on the [README.md](https://github.com/webpack-contrib/less-loader/blob/master/README.md#non-less-imports).
> Using webpack's resolver, you can import any file type. You just need a loader that exports valid Less code. Often, you will also want to set the issuer condition to ensure that this rule is only applied on imports originating from Less files:

### Actual Behavior

The loader chain is ignored. The imported file can not be converted to `less` compatible content. The source content of the file is provided to the `less` compiler.

This has been tested with a custom loader which just outputs a line to the console. This loader is not being called.

### Code

```js
// ./webpack.config.js
{
    entry: './index.js',
    mode: 'development',
    module: {
        rules: [
            {
                test: /\.less$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'less-loader'
                ]
            },
            {
                test: /\.less\.js$/,
                issuer: /\.less$/,
                use: [
                    {
                        loader: require.resolve('./test-loader.js')
                    }
                ]
            }
        ]
    }
}
```

```less
// ./main.less
@import './import.less.js';

body { background: green; }
```

```js
// ./index.js
import './main.less';
```

```js
// ./import.less.js
module.exports = 'body { color: red; }';
```

```js
// ./test-loader.js
module.exports = (source) => {
  console.log('It should call this loader', source);
  // parse content
  return source;
}
```

The error:
```
ERROR in ./main.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./main.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):


module.exports = 'body { color: red; }'
             ^
Unrecognised input
      Error in C:\Users\USER\Projects\less-issuer-test\import.less.js (line 1, column 15)
 @ ./main.less 2:12-125 9:17-24 13:15-29
 @ ./index.js 1:0-21
```

### How Do We Reproduce?

1. Create a new project with the `webpack` configuration above.
2. Create an entry point file (`index.js`), a `less` file (`main.less`) which imports a non-less file (`import.less.js`).
3. Create a loader (`test-loader.js`) to check if the import is being dragged through the loader chain.
4. Run webpack
5. Result

**Comment by evilebottnawi** [comment]
This error from less, expected, because we can't convert js file to less file

**Comment by Rall3n** [comment]
> This error from less, expected, because we can't convert js file to less file

@evilebottnawi But [non-less imports](https://github.com/webpack-contrib/less-loader/blob/master/README.md#non-less-imports) are a feature of the `less-loader`.

> Using webpack's resolver, you can import any file type. You just need a loader that exports valid Less code.

Are you telling me that this feature is expected to not work?

I'm not reporting an issue about `less` not being able to read the file, I'm reporting an issue about `less-loader` not dragging the file-to-be-imported through the loader chain.

**Comment by cap-Bernardito** [comment]
Thank you for contacting us.
Unfortunately, we have a description of deprecated behavior in the documentation that does not correspond to reality.
We'll fix readmy.

`Less` itself handles all imports, regardless of the extension, according to the [rules](http://lesscss.org/features/#import-atrules-feature-file-extensions).

That is, `Less` imports the file `import.less.js` as `import.less.less`, expecting to see a valid `less` syntax there. Sees `module.exports` and breaks.
