### ISSUE TITLE
Issue with less global-var

### ISSUE THREAD

**Issue by azymnis** [webpack-contrib/less-loader#39]
We use bower to manage our client dependencies. A number of these define a global variable `@{bower_path}` which we pass to `lessc` via the `--global-var` command line flag.

I understand that in less-loader we would need this to just be replaced with `~` so I wrote a loader that does this transformation. However, this loader only seems to process my own less files and not the files that are referenced in `@import` statements (seems like loaders are not called recursively). Any idea how to deal with this? For now, I'm just using a custom sed step to pre-process all less files before calling webpack.

**Comment by azymnis** [comment]
FYI this is my current sed hack:

    find ./bower_components/ -name *.less | xargs sed -i '.bak' 's/@{bower_path}\//~/g'
    find ./bower_components/ -name *.less.bak | xargs rm

**Comment by jhnns** [comment]
Is it possible to set the variable *before* importing the bower stuff?

Like:

```less
@bower-path: "...";

@import "stuff/from/bower";
```

Taking from the docs this is effectively the same as using the command line argument:

> Effectively the declaration is put at the top of your base Less file, meaning it can be used but it also can be overridden if this variable is defined in the file.

Besides that, you can pass [any less configuration](https://github.com/webpack/less-loader/blob/master/index.js#L37-L39) via loader parameters:

```javascript
module.exports = {
  module: {
    loaders: [
      {
        test: /\.less$/,
        loader: "less-loader?globalVar=my-background=red"
        // donnu if the = character should be url escaped here tbh
      }
    ]
  }
};
```

**Comment by azymnis** [comment]
Ah yeah declaring this at the top would work.

One more question: this was failing silently (the CSS was just not being generated) so I had to manually figure out what lines to comment out in order to get some CSS to be generated. Any chance that we could make less failures more verbose?

**Comment by jhnns** [comment]
Ehm ... errors encountered by LESS yield the loader to fail loudly.

There are two possibilities:
- Does LESS fail when you compile your files via `lessc` without the global var?
- The error is swallowed elsewhere. Are you using grunt/gulp/etc?

**Comment by khayredinov** [comment]
try
```
less-loader?{"globalVars":{"a":"green"}}
```

**Comment by Moinax** [comment]
Does someone figured this out ?

I tried something like @khayredinov (even with JSON.stringify to be sure) but the results is still the same

```javascript            
{
    test: /\.less/,
    include: [
       path.resolve(__dirname, 'src')
    ],
    loader: 'style-loader!css-loader?sourceMap!less-loader?' + JSON.stringify({
        sourceMap: {},
        globalVar: {
            imgPath: '/'
        }
    })
}
```

The less file

```less
.box-work {
  background: #000000 url("@{imgPath}bg/grip.png") 0 0 repeat;
}
```

The webpack error

```
ERROR in ./~/css-loader?sourceMap!./~/less-loader?{"sourceMap":{},"globalVar":{"imgPath":"/"}}!./src/components/Work/Work.less
Module build failed: variable @imgPath is undefined
 @ /.../Work/Work.less (line 34, column 26)
 near lines:
   .box-work {
     background: #000000 url("@{imgPath}bg/grip.png") 0 0 repeat;
 @ ./.../Work/Work.less 4:14-190 13:2-17:4 14:20-196
```

**Comment by SkReD** [comment]
Here is part of code where lessc cmd arguments are converts to options params. 
`global-var` argument is converting to `globalVars` options parameter. So you need to replace `globalVar` with `globalVars` and it should work


```javascript
switch (arg) {
            case 'v':
            case 'version':
                console.log("lessc " + less.version.join('.') + " (Less Compiler) [JavaScript]");
                continueProcessing = false;
                break;
            case 'verbose':
                verbose = true;
                break;
            case 's':
            case 'silent':
                silent = true;
                break;
            case 'l':
            case 'lint':
                options.lint = true;
                break;
            case 'strict-imports':
                options.strictImports = true;
                break;
            case 'h':
            case 'help':
                printUsage();
                break;
            case 'x':
            case 'compress':
                options.compress = true;
                break;
            case 'insecure':
                options.insecure = true;
                break;
            case 'M':
            case 'depends':
                options.depends = true;
                break;
            case 'max-line-len':
                if (checkArgFunc(arg, match[2])) {
                    options.maxLineLen = parseInt(match[2], 10);
                    if (options.maxLineLen <= 0) {
                        options.maxLineLen = -1;
                    }
                }
                break;
            case 'no-color':
                options.color = false;
                break;
            case 'no-ie-compat':
                options.ieCompat = false;
                break;
            case 'no-js':
                options.javascriptEnabled = false;
                break;
            case 'include-path':
                if (checkArgFunc(arg, match[2])) {
                    // ; supported on windows.
                    // : supported on windows and linux, excluding a drive letter like C:\ so C:\file:D:\file parses to 2
                    options.paths = match[2]
                        .split(os.type().match(/Windows/) ? /:(?!\\)|;/ : ':')
                        .map(function(p) {
                            if (p) {
                                return path.resolve(process.cwd(), p);
                            }
                        });
                }
                break;
            case 'line-numbers':
                if (checkArgFunc(arg, match[2])) {
                    options.dumpLineNumbers = match[2];
                }
                break;
            case 'source-map':
                options.sourceMap = true;
                if (match[2]) {
                    sourceMapOptions.sourceMapFullFilename = match[2];
                }
                break;
            case 'source-map-rootpath':
                if (checkArgFunc(arg, match[2])) {
                    sourceMapOptions.sourceMapRootpath = match[2];
                }
                break;
            case 'source-map-basepath':
                if (checkArgFunc(arg, match[2])) {
                    sourceMapOptions.sourceMapBasepath = match[2];
                }
                break;
            case 'source-map-map-inline':
                sourceMapFileInline = true;
                options.sourceMap = true;
                break;
            case 'source-map-less-inline':
                sourceMapOptions.outputSourceFiles = true;
                break;
            case 'source-map-url':
                if (checkArgFunc(arg, match[2])) {
                    sourceMapOptions.sourceMapURL = match[2];
                }
                break;
            case 'rp':
            case 'rootpath':
                if (checkArgFunc(arg, match[2])) {
                    options.rootpath = match[2].replace(/\\/g, '/');
                }
                break;
            case "ru":
            case "relative-urls":
                options.relativeUrls = true;
                break;
            case "sm":
            case "strict-math":
                if (checkArgFunc(arg, match[2])) {
                    options.strictMath = checkBooleanArg(match[2]);
                }
                break;
            case "su":
            case "strict-units":
                if (checkArgFunc(arg, match[2])) {
                    options.strictUnits = checkBooleanArg(match[2]);
                }
                break;
            case "global-var":
                if (checkArgFunc(arg, match[2])) {
                    if (!options.globalVars) {
                        options.globalVars = {};
                    }
                    parseVariableOption(match[2], options.globalVars);
                }
                break;
            case "modify-var":
                if (checkArgFunc(arg, match[2])) {
                    if (!options.modifyVars) {
                        options.modifyVars = {};
                    }

                    parseVariableOption(match[2], options.modifyVars);
                }
                break;
            case 'url-args':
                if (checkArgFunc(arg, match[2])) {
                    options.urlArgs = match[2];
                }
                break;
            case 'plugin':
                var splitupArg = match[2].match(/^([^=]+)(=(.*))?/),
                    name = splitupArg[1],
                    pluginOptions = splitupArg[3];

                plugin = pluginLoader.tryLoadPlugin(name, pluginOptions);
                if (plugin) {
                    plugins.push(plugin);
                } else {
                    console.error("Unable to load plugin " + name +
                        " please make sure that it is installed under or at the same level as less");
                    currentErrorcode = 1;
                }
                break;
            default:
                plugin = pluginLoader.tryLoadPlugin("less-plugin-" + arg, match[2]);
                if (plugin) {
                    plugins.push(plugin);
                } else {
                    console.error("Unable to interpret argument " + arg +
                        " - if it is a plugin (less-plugin-" + arg + "), make sure that it is installed under or at" +
                        " the same level as less");
                    currentErrorcode = 1;
                }
                break;
        }
```

**Comment by Moinax** [comment]
I think I tried both with and without trailing "s" without any result, but I will give it a try to be sure.

Regards,

**Comment by jhnns** [comment]
This is probably outdated. See also https://github.com/webpack-contrib/less-loader/issues/46#issuecomment-287869677

**Comment by cihadhoruzoglu** [comment]
@jhnns I can't figure it out with options parameter as you said. Here is my config;
```
{
        test: /\.less$/,
        use: extractLess.extract({
          use: [{
            loader: "css-loader"
          }, {
            loader: 'less-loader',
            options: {
              globalVars: "somevar=red"
            }
          }],
          // use style-loader in development
          fallback: "style-loader"
        })
      }
```

and here is the error;
```
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 281 bytes [entry]
        [0] ./~/css-loader!./~/less-loader?{"globalVars":"somevar=red"}!./src/assets/styles/example-style.less 281 bytes {0} [built] [failed] [1 error]
    ERROR in ./~/css-loader!./~/less-loader?{"globalVars":"somevar=red"}!./src/assets/styles/example-style.less
    Module build failed: variable @somevar is undefined
     near lines:
       span {
         background: @somevar;
       }
```

**Comment by jhnns** [comment]
Take a look [here](https://github.com/less/less.js/blob/b782411278a4916bec6ceaa4f6bb5cb56fd07620/bin/lessc#L498-L505).

The Less executable is parsing the options from the command line and assigning it to an object. I guess, your configuration should look like this:

```js
          {
            loader: 'less-loader',
            options: {
              globalVars: {
                somevar: 'red'
              }
            }
          }
```

**Comment by cihadhoruzoglu** [comment]
@jhnns thank you! it works!

**Comment by xuxiaoxiao312** [comment]
hey @jhnns  i meet the same  error just like @cihadhoruzoglu , and here is my config:
`      { 
        test: /\.less/,
        loader: "less-loader", 
       options: {
            globalVars: {
               'primary-color': 'blue'
            }
        }
      }
`
and here is the error;

> webpack-internal:///114:161 ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-6a482396","scoped":true,"hasInlineConfig":true}!./node_modules/vux-loader/src/after-less-loader.js!./node_modules/less-loader/dist/cjs.js!./node_modules/vux-loader/src/style-loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/AddressSearchBar.vue
Module build failed: 
  float: left;
  color: @primary-color;
Variable @primary-color is undefined
      in D:\Code\pregnotice-webapp\src\components\AddressSearchBar.vue (line 48, column 9)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-6a482396","scoped":true,"hasInlineConfig":true}!./node_modules/vux-loader/src/after-less-loader.js!./node_modules/less-loader/dist/cjs.js!./node_modules/vux-loader/src/style-loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/AddressSearchBar.vue 4:14-443 13:3-17:5 14:22-451
 @ ./src/components/AddressSearchBar.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/hospital/search.vue
 @ ./src/pages/hospital/search.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/utils/polyfill.js ./src/main.js

can you give me some help? thank you very much

**Comment by marudhupandiyang** [comment]
I'm trying to create a variable using the same. But could not achieve it for some reason.

     ERROR in ./node_modules/css-loader?sourceMap=true!./node_modules/less-loader/dist/cjs.js?{"sourceMap":true,"globalVars":{"myVar":"red"}}!./src/styles/app.less
     Module build failed:

     @color: @myVar;
                 ^
     Variable @myVar is undefined


Extract from webpack config

    .extract({
        fallback: 'style-loader',
        use: [
        'css-loader?sourceMap=true',
        {
                loader: "less-loader", options: {
                    sourceMap: true,
                    globalVars: {
                      myVar: process.cwd(),
                    }
          }}],
     })
