### ISSUE TITLE
Source-map files pointing to wrong less file

### ISSUE THREAD

**Issue by Dvd1234** [webpack-contrib/less-loader#393]
Hey Everyone. :)
This is with regards to **webpack less-loader**. Say, I have three files:-

1. **less0.less (empty)**
`(empty)`
2. **less1.less**
`@import 'less0.less'`
3. **less2.less**
```
    @import 'less1.less'
    @var-test: .trial;
    
    @{var-test}{
          color: red;
    }
```
I am generating Source-map for these files by webpack less-loader. The bundle.js.map, bundle.js files are being successfully generated.

My webpack.config.js:-
```
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const isProduction = process.env.NODE_ENV === 'production';

const config = {
    // First, let's define an entry point for webpack to start its crawling.
    entry: './src/index.js',
    // Second, we define where the files webpack produce, are placed
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
    },
    module: {
        rules: [
            { 
                test: /\.(le|c)ss$/, // .less and .css
                use: [ 
                    isProduction ? MiniCssExtractPlugin.loader : 'style-loader', 
                    {
                        loader: "css-loader",
                        options: {
                          sourceMap: true,
                        },
                      },
                      {
                        loader: "less-loader",
                        options: {
                          sourceMap: true,
                        },
                      },
                ],
            },
        ]
    },
    // Add an instance of the MiniCssExtractPlugin to the plugins list
    // But remember - only for production!
    plugins: isProduction ? [new MiniCssExtractPlugin()] : [],
    devtool: 'source-map',
};

module.exports = config;

```
Running webpack in development mode!

The generated files(bundle.js) are being used in an html file. Source files are being used for debugging in browser. Now in browser, it shows the .trial class to be in less0.less and not less2.less So, **Expected behavior** is to have shown **less2.less** as source for .trial class and not the one being shown:- 
https://i.stack.imgur.com/QiNQD.png

Could anyone please help me out if its an issue or if I need to tweak some setting. Thanks in advance. 

**USE CASE:** Say I have a file with less variables that has my configurations(Say less1.less). I am importing those settings in some other file(Say less2.less). Then, after Source-mapping, when trying to check source from source in dev-tool, it takes me to less1.less and not less2.less.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
Respect time of other developers

**Comment by evilebottnawi** [comment]
Every day I get 50-100 issues and unfortunately I cannot process them if everyone writes as they want
