### ISSUE TITLE
Having webpack as a peer dependency isn't quite accurate

### ISSUE THREAD

**Issue by kaiyoma** [webpack-contrib/less-loader#394]
- Operating System: Windows 10, Linux
- Node Version: 14.15.0
- NPM Version: 6.14.8
- webpack Version: (not used directly)
- less-loader Version: 7.0.2

### Expected Behavior

No warnings during package installation.

### Actual Behavior

```
warning "less-loader@7.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
```

### How Do We Reproduce?

I'm using less-loader in a Storybook project and I'm seeing a warning during package installation (see above). This peer dependency isn't quite accurate because I'm not using webpack (directly) in my project. Storybook comes with its own webpack installation, which means I won't be adding webpack to my package.json. I think this peer dependency should be removed.

**Comment by evilebottnawi** [comment]
Please open an issue in `storybook`, you need to have webpack when use less-loader otherwise PnP for yarn will be broken

**Comment by kaiyoma** [comment]
Storybook already includes webpack. That's why I don't need it as a dependency in my project. What issue would I file against Storybook?

**Comment by evilebottnawi** [comment]
What problem do we have? We need webpack in peer deps to working with npm v7 and pnp, also you need webpack and less to working with this loader

**Comment by kaiyoma** [comment]
In my situation, I don't install webpack myself, because it comes as a part of Storybook. Therefore, the webpack peer dependency will never be fulfilled and I'll always have a warning during package installation. It doesn't make sense for me to add webpack as a dependency.

I don't think the peer dependency is accomplishing anything here. If the user needs webpack, they'll install webpack. They don't need a peer dependency to tell them that.

**Comment by evilebottnawi** [comment]
>  We need webpack in peer deps to working with npm v7 and pnp

Do you read it?

**Comment by kaiyoma** [comment]
I'm not using npm (I'm using yarn).

**Comment by evilebottnawi** [comment]
> PnP

**Comment by kaiyoma** [comment]
What is that? I haven't heard of "pnp" in the context of npm.

**Comment by evilebottnawi** [comment]
https://classic.yarnpkg.com/en/docs/pnp/
