### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by githoniel** [webpack-contrib/less-loader#400]
## Bug

I meet bug in title when compile with less error.

## Version: 

less: 3.13.1
less-loader: 6.20

## What I found

my less option is 
![image](https://user-images.githubusercontent.com/17848159/103194736-8177f880-491b-11eb-9a6a-cc48aac3dcdf.png)

error is 
![image](https://user-images.githubusercontent.com/17848159/103194763-90f74180-491b-11eb-9b76-5a32e03167e8.png)

I  dont know why there is no more info.

https://github.com/webpack-contrib/less-loader/blob/78befcdf71c34231efefd977cfb107844eeffcbc/src/index.js#L45-L53

We check `lessError.filename` for existed but do not do this in constructor of `LessError` 

https://github.com/webpack-contrib/less-loader/blob/78befcdf71c34231efefd977cfb107844eeffcbc/src/LessError.js#L11

**Comment by alexander-akait** [comment]
Fixed, anyway please update to the latest version (`^7.2`)
