### ISSUE TITLE
TypeError: this.getOptions is not a function on 8.0.0, downgrading resolves

### ISSUE THREAD

**Issue by AtaS** [webpack-contrib/less-loader#408]
- Operating System: Ubuntu 20.04.1 LTS _on Windows Subsystem Linux - Windows 10_
- Node Version:  v14.15.2
- NPM Version: 6.14.10
- webpack Version:  4.44.2
- **less-loader Version: 8.0.0**

Downgrading to 7.3.0 resolved the issue.
Same exact issue exists for sass-loader 11.0.0 and downgrading works as well.

### Expected Behavior

No errors are expected.

### Actual Behavior

```
ERROR in ./.../styles/_style.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./.../styles/_style.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.lessLoader (.../node_modules/less-loader/dist/index.js:21:24)
 @ ./.../styles/_style.less 2:26-143 53:4-74:5 56:18-135
 @ ./....tsx
 @ multi @babel/polyfill ./....tsx
```

### Code

```js
...
{
  test: /\.less$/i,
  use: [
	  // Creates `style` nodes from JS strings
	  'style-loader',
	  // Translates CSS into CommonJS
	  'css-loader',
	  // Compiles Sass to CSS
	  'less-loader',
  ],
},
...
```

```js
// additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?
Please use the steps outlined.

**Comment by hosein2398** [comment]
Had the same problem.

**Comment by alexander-akait** [comment]
Because when you updating something you need to read changelog. You need webpack v5 to use latest version

**Comment by AtaS** [comment]
Yes, I've thought that was the issue after doing some read around but I've never updated it. 
I installed it from scratch with simply `npm install less-loader -D`.
Would it be possible to make `npm` install the compatible version due to existent dependency? I think at least providing a better error message might be more helpful because `this.getOptions is not a function` is not self explanatory that webpack 5 is required.

**Comment by alexander-akait** [comment]
@AtaS You should get warning/error about invalid peer deps from `npm`/`yarn`, if you want to improve error(s) you need open an issue about it in `npm`/`yarn` (npm v7 should fix it)

**Comment by billyvg** [comment]
If you're getting this error with storybook, it's because it's still using webpack 4 (see https://github.com/storybookjs/storybook/issues/14044)

**Comment by JasonKleban** [comment]
The community might benefit from a mention of the version compatibilities in the readme.  The change log is a bit buried at this point.
