### ISSUE TITLE
Webpack 5 not outputting LESS styles?

### ISSUE THREAD

**Issue by RyanPWalker** [webpack-contrib/less-loader#409]
- Operating System: MacOS Big Sur latest
- Node Version: 14.15.4
- NPM Version: 6.14.10
- webpack Version: ^5.21.2
- less-loader Version: ^8.0.0

### Expected Behavior
I expect to see styles when running in dev mode, and I expect to see an outputted css file in the `dist` folder when running a prod build.

### Actual Behavior
When running a dev build, the js loads just fine, but none of the styles are loaded.  When running a prod build, the js is output to the `dist` folder as expected, but no css file is generated.

### Code
Please see my branch code [here](https://github.com/RyanPWalker/react-client-boilerplate/tree/update-packages)
Also, [here](https://stackoverflow.com/questions/66146177/webpack-5-not-outputting-less-styles) is my SO question that no one answered, so I assume it's a bug.

### How Do We Reproduce?
Simply run `yarn dev` for localhost and `yarn build` for a prod build then check the `dist` folder.

**Comment by ryanjchr** [comment]
Having the same problem. Just upgraded from Webpack 4 to 5, upgraded less and less-loader and can't get my LESS styles to be included in the build, either with style-loader or mini-css-extract-plugin's loader.

**Comment by alexander-akait** [comment]
Remove `"sideEffects": false,` from `package.json`, CSS has always side effects, also you don't need for app, it makes sense only for libraries
