### ISSUE TITLE
Use docs configure, but got less.webpackLoaderContext deprecated.

### ISSUE THREAD

**Issue by nuintun** [webpack-contrib/less-loader#413]
- Operating System: WIN 10
- Node Version: 15
- NPM Version: 7
- webpack Version: 5
- less-loader Version: 8.1.0

### Code

```js
{
  test: /\.less$/i,
  use: [
    {
      loader: MiniCssExtractPlugin.loader
    },
    {
      loader: '@teamsupercell/typings-for-css-modules-loader'
    },
    {
      loader: 'css-loader',
      options: {
        esModule: true,
        importLoaders: 2,
        modules: { auto: true, localIdentName, exportLocalsConvention: 'camelCaseOnly' }
      }
    },
    {
      loader: 'postcss-loader'
    },
    {
      loader: 'less-loader',
      options: { lessOptions: { modifyVars: themeVars, javascriptEnabled: true } }
    }
  ]
}
```

![企业微信截图_1618198511842](https://user-images.githubusercontent.com/1730277/114350966-85fbb080-9b9c-11eb-91df-3b6377ec55f1.png)

**Comment by meskill** [comment]
I've created pr to fix this issue - #414

**Comment by andy0130tw** [comment]
@nuintun Are you embedding less inside frameworks e.g., Vue? I also encountered the same bug, but cannot reproduce in (1) the setup in README (2) with mini-css-extract-plugin; dependencies below:

```json
{
  "devDependencies": {
    "css-loader": "^3.6.0",
    "less": "^3.13.1",
    "less-loader": "^8.0.0",
    "mini-css-extract-plugin": "^1.3.7",
    "webpack": "^5.32.0",
    "webpack-cli": "^4.6.0"
  }
}
```

**Comment by andy0130tw** [comment]
I add a line in `dist/utils.js` to make webpack bail out as follows:

```diff
    if (typeof lessProcessor.webpackLoaderContext === "undefined") {
        Object.defineProperty(lessProcessor, "webpackLoaderContext", {
          configurable: true,

          get() {
+           throw new Error(1)
            return webpackContextDeprecated(loaderContext);
          }

        });
      }
```

And it turns out to error in some files related to Vue. Not sure if it's related.

**Comment by nuintun** [comment]
@andy0130tw I use react, and all dependencies was embedded.

**Comment by alexander-akait** [comment]
we are working on fix

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack-contrib/less-loader/releases/tag/v8.1.1
