### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by MaxusAdmin** [webpack-contrib/less-loader#416]
- Operating System: linux
- Node Version: v14.16.1
- NPM Version: 6.14.12
- webpack Version: 4.44.2
- less-loader Version: 8.0.0

### Expected Behavior
Build the project without errors as it was in version 7.3.0

### Actual Behavior
Build the project with errors

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?
in the file at the path /v8. 1. 1/src/index.js the function this.GetOptions(schema) is not defined since it was in the version /v7.3.0/src/index.js

import { getOptions } from "loader-utils" doesn't in file  /v8. 1. 1/src/index.js

**Comment by alexander-akait** [comment]
Please read changelog before updating https://github.com/webpack-contrib/less-loader/releases/tag/v8.0.0

> minimum supported webpack version is 5
