### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by denglai** [webpack-contrib/less-loader#433]
- Operating System:os 11.5.1
- Node Version:v14.17.3
- NPM Version:6.14.13
- webpack Version:4.44.2
- less-loader Version:7.3.0

### Expected Behavior

Build the project without errors as it was in version 7.3.0

### Actual Behavior

TypeError: this.getOptions is not a function

### Code

```js
// webpack.config.js
 lessOptions:{
        strictMath: false,
        noIeCompat: true,
        javascriptEnabled: true,
      },
      implementation: require("less"),
```

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version of less-loader

**Comment by denglai** [comment]
> You need webpack v5 to use the latest version of less-loader

Webpack V5 is required for less-Loader V8，but my less-loader is v7.3.0
