### ISSUE TITLE
webpack less-loader css modules fail

### ISSUE THREAD

**Issue by victorykong** [webpack-contrib/less-loader#439]
### Bug report

Can't css modularity and non-modularity (global css) of less files coexist?
![image](https://user-images.githubusercontent.com/50655436/134510688-04a38d77-701c-4fd5-b48b-790b4dcd5af4.png)

### Actual Behavior

The webpack failed to be built, which will lead to failure if it does not recognize the less file, or only recognizes one of module.less and .less.

### Expected Behavior

As with the file suffix:. less should be `import "./index.less"`,which will affect the global style. While. module.less should be `import styles from "./index.module.less"` and modularized by css.

### How Do We Reproduce?

https://github.com/victorykong/webpack-replay
https://github.com/victorykong/webpack-replay.git

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

Looking forward to your reply!

**Comment by victorykong** [comment]
@sophiebits @ericclemmons @wolever

**Comment by alexander-akait** [comment]
Look at error message, you apply `less-loader` twice

**Comment by alexander-akait** [comment]
And do not spam pings

**Comment by alexander-akait** [comment]
Solutions:
```

        test: /\.module\.less$/,
        use: [
          "vue-style-loader",
          {
            loader: "css-loader",
            options: {
              modules: true,
              localIdentName: "[local]_[hash:base64:8]",
            },
          },
          "less-loader",
        ],
      },
      {
        test: /\.less$/,
        exclude: /\.module\.less$/
        use: [
          "vue-style-loader",
          {
            loader: "css-loader",
            options: {
              modules: false,
            },
          },
          "less-loader",
        ],
      },
```

**Comment by victorykong** [comment]
> Solutions:
> 
> ```
> 
>         test: /\.module\.less$/,
>         use: [
>           "vue-style-loader",
>           {
>             loader: "css-loader",
>             options: {
>               modules: true,
>               localIdentName: "[local]_[hash:base64:8]",
>             },
>           },
>           "less-loader",
>         ],
>       },
>       {
>         test: /\.less$/,
>         exclude: /\.module\.less$/
>         use: [
>           "vue-style-loader",
>           {
>             loader: "css-loader",
>             options: {
>               modules: false,
>             },
>           },
>           "less-loader",
>         ],
>       },
> ```

Thank you very much. It really solved my problem. But I would like to ask again, for example,. module.less should not have hit my first rule, and then it will not match again? I also specially wrote this rule before less in order to match module.less as soon as possible.

**Comment by alexander-akait** [comment]
Order doesn't matter here, only `test` make sense
