### ISSUE TITLE
not find prependData and apendData information in README.md

### ISSUE THREAD

**Issue by waitInHope** [webpack-contrib/less-loader#458]
Documentation Is: I need use appendData and prependData options. But I can not find details about these. So I look up from webpack website to less-loader github website. Finally I get it from change log in 2020-04-24.

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I need use appendData and prependData options. But I can not find details about these. So I look up from webpack website to less-loader github website. Finally I get it from change log in 2020-04-24.

added the appendData option (https://github.com/webpack-contrib/less-loader/issues/336) ([fb94605]
added the prependData option (https://github.com/webpack-contrib/less-loader/issues/327) ([9df8755]

### Your Proposal for Changes
I suggest adding prependData and appendData details on README.md.

**Comment by alexander-akait** [comment]
They will be removed in favor https://github.com/webpack-contrib/less-loader#additionalData, please read https://github.com/webpack-contrib/less-loader/releases/tag/v7.0.0
