### ISSUE TITLE
Confusing `imports` explanation

### ISSUE THREAD

**Issue by Wzb3422** [webpack-contrib/less-loader#459]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

At [README.md#imports](https://github.com/webpack-contrib/less-loader/blob/2952cbe0cfaa853730420921f2e97d1f36f79a59/README.md?plain=1#L502-L504)
> Using ~ is deprecated and can be removed from your code (we recommend it), but we still support it for historical reasons. Why you can removed it? The loader will first try to resolve @import as relative, if it cannot be resolved, the loader will try to resolve @import inside [node_modules](https://webpack.js.org/configuration/resolve/#resolve-modules). Just prepend them with a ~ which tells webpack to look up the [modules](https://webpack.js.org/configuration/resolve/#resolve-modules).

I found it confusing that although `~` is deprecated and recommended to be removed (as mentioned at the first sentence), however, the README still tells me to prepend with a `~` to tell webpack to look up the modules (as mention at the last sentence).
Its inconsistency makes me confusing.

### Your Proposal for Changes

Because `~` is deprecated and is not recommended anymore. The README is not supposed to tell me to prepend `~`.

**Comment by alexander-akait** [comment]
Done https://github.com/webpack-contrib/less-loader/pull/472
