### ISSUE TITLE
Cannot use modifyVars to modify a file path variable

### ISSUE THREAD

**Issue by ghost** [webpack-contrib/less-loader#46]
less-loader appear to have some escaping issues when I try to modify a variable that includes a path:

```
  {
    test: /\.less$/,
    loader: 'less-loader',
    query: {
      modifyVars: {
        'root-path': '"../../../root/"',
      }
    }
  },
```

This appears to over write @root-path for simple values like 'root', but some combination of .., /, and " makes this fail.

edit: Looks like this fails because of this line:

```
var query = loaderUtils.parseQuery(this.query);
```

**Comment by dthielman** [comment]
@davidye For what it's worth, LoaderUtils is a dependency (https://github.com/webpack/loader-utils). I, too, am having some issues with `modifyVars`, and I'll try to post here if my solution resolves yours. 

Cheers!

**Comment by jhnns** [comment]
I think, this is outdated. With webpack 2, you are able to pass the options directly to the loaders. Unfortunately, they haven't documented their Node.js API, just their dash-cased CLI options. You need to check in the [Less executable how these options are applied](https://github.com/less/less.js/blob/3.x/bin/lessc).
