### ISSUE TITLE
Invalid dependencies when webpack alias same with workspace folder

### ISSUE THREAD

**Issue by LitileXueZha** [webpack-contrib/less-loader#512]
Webpack alias:
```js
// <workspace_folder>/webpack.config.js
{
  resolve: {
    alias: {
      a: path.join(__dirname, 'a'),
      other: path.join(__dirname, 'a'),
    },
  },
}
```
Directories tree:
```txt
<workspace_folder>
├── a
│   ├── b.less
│   └── c.less
├── src
│   ├── index.less
│
```
Source code:
```less
// <workspace_folder>/src/inde.less
@import '../a/c.less';
@import 'a/b.less';     // <== Invalid deps
@import 'other/b.less'; // ok
```

https://github.com/webpack-contrib/less-loader/blob/783ad2681c53667eff27a62971a114d1af6fbf11/src/utils.js#L118

https://github.com/less/less.js/blob/4d3189c05175dfd8aab505ec19c7f5724f145295/packages/less/src/less-node/file-manager.js#L32

While `less-node` load `'a/b.less'` successful, because it add <workspace_folder> to search paths, the dependency is still relative.

**Comment by alexander-akait** [comment]
Sorry, I don't undestand, all works as expected, you setup alias so you got it

**Comment by alexander-akait** [comment]
@LitileXueZha Sorry for delay, we use this https://github.com/webpack-contrib/less-loader/blob/master/src/index.js#L104, so it should not happend, can you create a simple reproducible example?

**Comment by LitileXueZha** [comment]
@alexander-akait Check it => https://github.com/LitileXueZha/less-webpack-issue

**Comment by alexander-akait** [comment]
Sorry for delay, I see the problem, WIP on this
