### ISSUE TITLE
Using of extend feature from less

### ISSUE THREAD

**Issue by igorline** [webpack-contrib/less-loader#52]
Is it possible to use extend notation in any form?

```
@extend .col-md-3;
```

This way I'm getting it skipped.

```
&:extend(.col-md-3);
```

This way I receive error in webpack

```
Module build failed: 
    .item {
      ^
      Invalid property name
```

**Comment by Yunkou** [comment]
+1

**Comment by shinygang** [comment]
+1

**Comment by jeremyadavis** [comment]
Having this issue as well using bootstrap mixins.

```
.make-row(@gutter: @grid-gutter-width) {
  margin-left:  (@gutter / -2);
  margin-right: (@gutter / -2);
  &:extend(.clearfix all);
}
```

**Comment by jhnns** [comment]
extend is working as expected afaik, this one is probably outdated. If not, please re-open with a minimal example repository to reproduce the error.
