### ISSUE TITLE
`@import ` cannot recursively look up the npm package directory

### ISSUE THREAD

**Issue by treeFuck** [webpack-contrib/less-loader#524]
### Bug report

```js
<node_modules>
├── lessPkg1 @1.0.0
│    └── index.less
├── lessPkg2
│    ├── index.less
|    └── node_modules
|        └──lessPkg1 @2.0.0
|            └── index.less
│
```
In lessPkg2/index.less
```less
@import "lessPkg1/index.less"
```

In webpack, it will match lessPkg1 @1.0.0/Index.less, because of [the code here](https://github.com/webpack-contrib/less-loader/blob/v11.1.3/src/utils.js#L116).

Actually, I hope it can match to lessPkg1 @ 2.0.0/Index.less.

### Actual Behavior

Breakpoint debugging webpack, I found the `loadFile` function in [here](https://github.com/less/less.js/blob/v4.1.3/packages/less/src/less-node/file-manager.js#L15)，It will only match two paths:
+ `currentDirectory`: The path of lessPkg2
+ `·`: The node_modules directory of my project

so, it it will match lessPkg1 @1.0.0/Index.less.
### Expected Behavior

In vite, it will match lessPkg1 @2.0.0/Index.less, because of [the code here](https://github.com/vitejs/vite/blob/v4.4.9/packages/vite/src/node/plugins/css.ts#L2003). it will use [`resolvePackageData`](https://github.com/vitejs/vite/blob/v4.4.9/packages/vite/src/node/packages.ts#L87) function to resolve `lessPkg1/index.less`.

### How Do We Reproduce?

Using my example above, it can be reproduced.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 217.31 MB / 16.00 GB
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
  Packages:
    css-loader: ^6.8.1 => 6.8.1
    html-webpack-plugin: ^5.5.1 => 5.5.3
    less-loader: ^11.1.3 => 11.1.3
    style-loader: ^3.3.3 => 3.3.3
    webpack: ^5.86.0 => 5.88.2
    webpack-cli: ^5.1.4 => 5.1.4

**Comment by alexander-akait** [comment]
Sorry for delay, this is an intresting problem... 

We prefer to use built-in less loading logic firstly for compatibility reasons, for example, if you have your project without bundler, just less files and build them using less CLI you can rely on this behaviour (yes, for me it is strange too, but this is how less does), on the other side it is a bug, I want to say - Less should fix it in your code (it is a right solution), but I think they will not fix it, so I will try to find a better logic here

**Comment by treeFuck** [comment]
You can use the example here to reproduce: [less-import-test](https://github.com/treeFuck/less-import-test)

**Comment by treeFuck** [comment]
You can use the example here to reproduce: [less-import-test](https://github.com/treeFuck/less-import-test)

**Comment by alexander-akait** [comment]
@treeFuck there is a bug on the vite side

Run in command line:

```bash
$ lessc webpack-test/index.less
```

Output is:
```
.test {
  background-color: #f40;
}
* {
  padding: 0;
  margin: 0;
}
.test {
  height: 200px;
  width: 200px;
}
```

And our output is the same. 

Why? Because less has a such behaviour (you can open an issue in `less` repo about it), yeah, it is strange, but we want to be align with resolving/importing files to the original tool.

Feel free to feedback
