### ISSUE TITLE
Imports Out of Order in Output

### ISSUE THREAD

**Issue by garretto** [webpack-contrib/less-loader#57]
I'm using the Extract Text Plugin with less-loader to import a main.less files with several imports. I have a reset LESS stylesheet at the beginning which should start at the beginning of the compiled CSS. However, my imports are not being output in order. It works fine when I use the regular lessc compiler.

**Comment by jhnns** [comment]
The order of the extracted text is based on the order of `require()` calls inside the bundle. If you want to ensure that the output of `index.scss` is before all the other rules, you need to `require("./index.scss")` before requiring all the components.

See also https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200

**Comment by anonymous0374** [comment]
@jhnns no, 'require' does not solve the order issue at all
