### ISSUE TITLE
loading bootstrap problem

### ISSUE THREAD

**Issue by Ognian** [webpack-contrib/less-loader#59]
When trying to import bootstrap `import Bootstrap from 'bootstrap/less/bootstrap.less';`
I'm getting the following error:

```
ERROR in ./~/less-loader!./~/css-loader!./~/bootstrap/less/bootstrap.less
Module build failed: CssSyntaxError: /storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/bootstrap/less/bootstrap.less:7:1: Unknown word
    at Input.error (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/input.js:61:21)
    at Parser.unknownWord (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/parser.js:479:26)
    at Parser.word (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
    at parse (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/lib/processCss.js:165:11)
    at Object.module.exports (/storage/safe/ogi-it/Projekte/LIMS/LIMS_src/LIMS_v2/node_modules/css-loader/lib/loader.js:22:2)
 @ ./~/bootstrap/less/bootstrap.less 4:14-100

```

line 7 of bootstrap.less contains a comment :`// Core variables and mixing`
any ideas how to fix?

**Comment by eduardonunesp** [comment]
Same here 

```
ERROR in ../~/bootstrap/dist/css/bootstrap.css
Module parse failed: /Users/eduardonunesp/Enterprises/FAPL/browser/node_modules/bootstrap/dist/css/bootstrap.css Line 7: Unexpected token {
You may need an appropriate loader to handle this file type.
|  */
| /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
| html {
|   font-family: sans-serif;
|   -webkit-text-size-adjust: 100%;
 @ ./index.js 3:0-43
```

Conf

```
var path = require('path');

module.exports = {
  context: path.resolve('js'),
  entry: "./index",
  output: {
    path: path.resolve('build/js/'),
    publicPath: '/public/assets/js/',
    filename: "bundle.js"
  },

  devServer: {
    contentBase: "public",
  },

  module: {
    loaders: [
      {test: /\.html$/, loader: 'raw',exclude: /node_modules|bower_components/},
      {test: /\.css$/, loaders: ['style-loader', 'css-loader', 'postcss-loader'], exclude: /node_modules|bower_components/},
      {test: /\.less$/, loader: 'style-loader!css-loader!less-loader', exclude: /node_modules|bower_components/},
      {test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },
      {test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,   loader: "url?limit=10000&mimetype=application/font-woff" },
      {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,    loader: "url?limit=10000&mimetype=application/octet-stream" },
      {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,    loader: "file" },
      {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,    loader: "url?limit=10000&mimetype=image/svg+xml" },
      {test: /^((?!config).)*\.js?$/, exclude: /node_modules/, loader: 'babel?cacheDirectory'},
      {test: /\.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/, loader: 'file', exclude: /node_modules|bower_components/},
      {test: /\.js$/, loader: 'babel-loader', exclude: /node_modules|bower_components/, query: {
          presets: ['es2015']
        }
      }
    ]
  }
};
```

**Comment by BerndWessels** [comment]
Hi

I have the same issue.

I worked around it by importing my own less files

`import styles from './index.less';`

which then imports bootstrap

`@import '~bootstrap/less/bootstrap.less';`

The issue seems to be that if you directly import that the less file still somehow gets processed by the css-loader which doesn't like things like // inline comments.

Would be good if someone could have a deeper look into this.

Cheers
Bernd

**Comment by frob** [comment]
Yup still having the same issue.

**Comment by xcarpentier** [comment]
I used this order and it's works for me : 
"style-loader!css-loader!postcss-loader!less-loader"
[...]
postcss: function () {
     return [autoprefixer];
 },

**Comment by jhnns** [comment]
Sorry, there is not enough information to reproduce this. Please provide a minimal test repository that demonstrates the problem so I can check that out. Try to remove as much stuff as possible since it helps tracking down the problem.

**Comment by hemanthkumarcb** [comment]
getting below error while including bootstrap.less
VM66303:1 Uncaught Error: Module parse failed: \bootstrap\less\bootstrap.less Unexpected character '@' (8:0)
You may need an appropriate loader to handle this file type.
| 
| // Core variables and mixins
| @import "variables.less";
| @import "mixins.less";

=====
my import 
import '../less/style.less';
import '../node_modules/bootstrap/less/bootstrap.less';
=-==========================
webpack config
use: extractLess.extract({
          use: [{
            loader: 'css-loader', options: { url: false },
          }, {
            loader: 'less-loader',
          }],
          fallback: 'style-loader',

**Comment by frob** [comment]
@michael-ciniawsky why was this closed?

**Comment by d3viant0ne** [comment]
It's from 2015, does not have the requested feedback from the OP & is not a bug, people use bootstrap / less every day without issue.

This is question about a configuration issue, those belong on StackOverflow.

If you have a specific issue that is reproducible in code we can access, feel free to open a new issue.
