### ISSUE TITLE
generating SourceMap

### ISSUE THREAD

**Issue by nicolabortignon** [webpack-contrib/less-loader#60]
following up on @mtscout6 SourceMap implementation.
I have the following issue.
If i call this:

``` javascript
loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap' 
```

everything works as supposed.

But if write something like: 

``` javascript
loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap' 
```

then the sourceMap doesn't have the generated appended hash values ( ie: ___rhfs2), while the CSS does have it.

What am i doing wrong ?

**Comment by jhnns** [comment]
Could you check this against the latest version of the less-loader? If it's still relevant, please re-open with a small test repository to reproduce the error.
