### ISSUE TITLE
ERROR in Object.keys called on non-object

### ISSUE THREAD

**Issue by wz2b** [webpack-contrib/less-loader#63]
I am working on a webpack-es6-angular (1.x) project and am trying to incorporate my styles.   in webpack config:
    `{ test: /\.less$/, loader: 'style!css!less' }`

When I add this:
   `require("./styles/app.less");`

I get:
    `ERROR in Object.keys called on non-object
     @ ./app/styles/app.less 4:14-120`

It's a really simple .less file, no imports or anything.  I don't know how to debug it, or even whether or not it's really a less-loader problem.

**Comment by jhnns** [comment]
Could you check this against the latest version of the less-loader? If it's still relevant, please re-open with a small test repository to reproduce the error.
