### ISSUE TITLE
Conflict with file loading Less plugins?

### ISSUE THREAD

**Issue by fortes** [webpack-contrib/less-loader#64]
I'm trying to use `less-loader` along with [`less-plugin-load-json`](https://github.com/fortes/less-plugin-load-json), however it looks like the `less-loader` override of `fileLoader` prevents the plugin from running (since it accepts and reads all files). Is there a way around this?

**Comment by cap-Bernardito** [comment]
I think you need to use `less PreProcessor` like here,
https://www.npmjs.com/package/less-plugin-js-vars

or `loader` like here
https://github.com/tompascall/js-to-styles-var-loader
