### ISSUE TITLE
How to add a plugin (string replace) ?

### ISSUE THREAD

**Issue by BerndWessels** [webpack-contrib/less-loader#65]
Hi
I need to replace a string in my less files before they get compiled. But I can't figure out how to add a less plugin, the documentation is not really helpful here.

This is the important part of my `webpack.config`:

```
  // LESS LOADER
  var lessLoader = {
    test: /\.less$/,
    loader: (!BUILD || TEST) ? 'style!css!less!postcss' :
      // Extract less/css files in production builds
      ExtractTextPlugin.extract(
        'css?sourceMap!less?sourceMap!postcss'
        )
  };

  // Add cssLoader to the loader list
  config.module.loaders.push(lessLoader);

```

My question is, how do I get a less-loader plugin into that config shown above that can replace strings in the less files before they get processed?

Thank you
Bernd

**Comment by jiaweihli** [comment]
You can use `string-replace-loader` as a preLoader in webpack.

**Comment by sandro-csimas** [comment]
@michael-ciniawsky , do your solve this problem? I'm also trying to replace but is not working because the file is loaded using @import.

**Comment by sandro-csimas** [comment]
@jiaweihli , any ideas when the file is processed using less @import?

**Comment by l0g1c-80m8** [comment]
```
Module parse failed: Unexpected character '@' (1:0)
File was processed with these loaders:
 * ../../node_modules/string-replace-loader/index.js
You may need an additional loader to handle the result of these loaders.
```

Tried to group it with css loader and style loader but it doesn't work
