### ISSUE TITLE
Feature request for dynamic modifyVars

### ISSUE THREAD

**Issue by EloB** [webpack-contrib/less-loader#69]
I would like to have a single configuration for `mobile`, `tablet` and `desktop` entries so you don't have to start 3 webpack instances with different configs for each device. See my example below.

I know that media queries exists but I need to strip out unnecessary css (My market is sensitive to file sizes) without ruin the less source maps.

If there is any other way of doing this feel free to tell me.

**webpack.config.js**

``` js
var path = require('path'),
  ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: 'source-map',
  entry: {
    mobile: './app/index',
    tablet: './app/index',
    desktop: './app/index'
  },
  output: {
    filename: '[name].js',
    path: path.join(__dirname, 'dist')
  },
  module: {
    loaders: [
      {
        test: /\.less$/,
        loader: ExtractTextPlugin.extract(
          'css?sourceMap!less?{"sourceMap":"", "modifyVars":{"device":"[name]"}}'
        )
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin('[name].css')
  ]
};
```

**app/index.js**

``` js
require('./index.less');
```

**app/index.less**

``` less
body {
  // Include style to all devices
  & when(@device = mobile) {
    // Only for mobile
  }
  & when(@device = tablet) {
    // Only for tablet
  }
  & when(@device = desktop) {
    // Only for desktop
  }
}
```

**Comment by zephraph** [comment]
Heh, that's exactly what I need too. Different scenario, but same use case.

**Comment by zephraph** [comment]
So I've looked into this a little bit. This loader users the webpack [loader-utils](https://github.com/webpack/loader-utils) package to do stuff with. It has a method called [interpolatename](https://github.com/webpack/loader-utils#interpolatename) which gives the exact name resolution we're looking for. I still haven't quite figured out where the options are being passed in, but I'm assuming all we'd need to do is search for modifyVars or globalVars and call name interpolation on their values.

**Comment by zephraph** [comment]
I've tried my hand at doing this myself, but I'm a bit stuck and super sleepy so I'm going to leave it where it's at tonight. Checkout #70 to see the PR and let me know if you can figure out what I'm doing wrong. 

@jhnns If you or one of the other contributors get some free time this would be an awesome feature to have! (That I'm willing to do the work for, just got to work out the kinks).

**Comment by zephraph** [comment]
As an update, the PR is now passing the unit tests I wrote. There were a few wonky things I did wrong last night, but it all seems to be working well now. @EloB check it out.

**Comment by zephraph** [comment]
Yeah, it's not so done. The context provided to a loader is localized to the file that it's loading in. In theory that sounds like what you want, but what you actually want is for `[name]` to be interpolated with the name of the chunk that's currently being compiled. At this point I'm not even convinced that this is even possible. Unfortunately I need something similar to this so I'm still searching for an alternate solution.

**Comment by EloB** [comment]
Nice! :+1:

**Comment by orius123** [comment]
@EloB @zephraph I'm trying to achieve the same for creating different themes for my app, but it doesn't work, and I see from the PR comment https://github.com/webpack-contrib/less-loader/pull/70#issuecomment-165750018 that it can't. did you find another way / have an idea how to solve it?

**Comment by michael-ciniawsky** [comment]
Unfortunately this simply won't work with the way `less-loader` (`webpack`) handles CSS, the context is 'scoped' to the file with an input => output mapping
