### ISSUE TITLE
Source maps not working when using Bootstrap's less files

### ISSUE THREAD

**Issue by juliostanley** [webpack-contrib/less-loader#78]
Hi. Thanks for the project!

When loading bootstrap less, and source maps are enabled through the query string, an unhandled error occurs.

Caused by the less.js dependency:
https://github.com/less/less.js/issues/2761

Using:
@import "~bootstrap/bootstrap"

When I remove all &:extend(.clearfix all); from Bootstrap's source code. It works.

Suggestions?

**Comment by laurenskling** [comment]
are you supposed to @import "~bootstrap/less/bootstrap" ?
