### ISSUE TITLE
Loader does not accept my `paths`

### ISSUE THREAD

**Issue by wspringer** [webpack-contrib/less-loader#81]
If I'm setting the [`paths` option](http://lesscss.org/usage/#command-line-usage-options) to add another  load path for my less files, then webpack fails with an error:

```
ERROR in ./index.less
Module build failed: Cannot resolve 'file' or 'directory' ./font-awesome/less/font-awesome.less in /Users/wilfred/workspace/lesstest
 @ /Users/wilfred/workspace/lesstest/index.less (line 1, column 0)
 near lines:

   @import "font-awesome/less/font-awesome.less";
```

It appears the `paths` variable is completely disregarded, and the `WebpackFileManager` used internally is unable to resolve the file. Since I'm still pretty new to Webpack, I'm not sure if it violates a design principle, for all practical purposes, it would be great if the loader would support the `paths` property. If it _does_ violate a design principle, then it would be really convenient if the less-loader would inform anyone attempting to use the `paths` property that it is not supported.

**Comment by jhnns** [comment]
Yes, the path option is currently not supported. Sorry about that :disappointed:.

If you want to import stuff from a package, you need to prepend it with a `~`. In your example, that would be ` @import "~font-awesome/less/font-awesome.less";`

There has been discussion about this lately: #74 #75

**Comment by jhnns** [comment]
Starting with less-loader 4, you can now [choose between the webpack resolver and the less resolver](https://github.com/webpack-contrib/less-loader#imports).
