### ISSUE TITLE
Remove synchronous compilation/enhanced-require support

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/less-loader#84]
We should remove the synchronous path from the less-loader. It makes the code a lot harder to understand and impairs contribution. [enhanced-require](https://github.com/webpack/enhanced-require) is now unmaintained for 2 years and @sokra is recommending to use `target: "node"` in order to prepare your bundle for the server-side.

Additionally synchronous compilation is really inefficient and may slow down the application bootstrap significantly.

I've added a deprecation warning to the code so people have the chance to give us feedback. Maybe there's a use-case we haven't seen yet.

**Comment by zwjjap** [comment]
# 

> [`**__**`](

- 

- [ ] 1. url

)
