### ISSUE TITLE
Using sourcemaps breaks my font loading

### ISSUE THREAD

**Issue by laurenskling** [webpack-contrib/less-loader#87]
if i use the loader like this:

> ```
>   {
>     test: /\.less?$/,
>     loader: 'style!css?sourceMap!less?sourceMap',
>   },
> ```

I can see my less files in debugging, which is great. But now my (bootstrap glyphicons) font doesn't load. It tries to get it from `/` . My guess is it doesn't get:

> url('@{icon-font-path}@{icon-font-name}.ttf') format('truetype'),

correctly with the sourcemaps?

Using the loader without sourceMap makes the font work perfectly.

**Comment by hiyangguo** [comment]
Hi,@laurenskling ,I also appeared the same situation.
How do you resolve this problems?
Than you very much.

**Comment by laurenskling** [comment]
I can't remember where; but somewhere it was explained that sourceMap support wrongly prepends the URL twice with your path (or something in the likes).
Hardcoding the url to your publicPath will fix it:
```
output: {
  publicPath: debug ? 'http://localhost:8000/build/' : '/build/',
}
```

**Comment by hiyangguo** [comment]
thx very much.:smile:
