### ISSUE TITLE
2x times lower performance using ExtractTextPlugin

### ISSUE THREAD

**Issue by Tom910** [webpack-contrib/less-loader#88]
Hello.

I ran into a performance problem, I have a great app that uses less with config

```
loaders: [
  {
    test: /\.less$/,
    loader: ExtractTextPlugin.extract('style', 'css!autoprefixer?{browsers:["> 5%","Firefox >= 24","Explorer >= 10","Chrome >= 24","Opera >= 12","Safari >= 6"]}!less?-compress')
    },
]
plugins: [
  new ExtractTextPlugin(
    '[name].css'
  ),
]
```

With this configuration, assembly time is 120 - 130 seconds.

If the change in the loader
`
loader: 'style!css!autoprefixer?{browsers:["> 5%","Firefox >= 24","Explorer >= 10","Chrome >= 24","Opera >= 12","Safari >= 6"]}!less?-compress'
`
That assembly is already 85 seconds. However, already a part of the files is not less fall into assembly.

All files are less connected to the master file and variable myxines
`@import '../common/common';`
What it seems to me, too, it reduces productivity.

How can I lower the build time less files?

**Comment by naugtur** [comment]
I noticed ExtractTextPlugin is causing less-loader to put multiple copies of @imported things in resulting file. might be the cause.

**Comment by csvan** [comment]
@naugtur do you know any way to work around this?

**Comment by naugtur** [comment]
I found only one way around it. Instead of importing less files in js modules, I imported only the main one and made it automatically include all less files in subdirectories.

It's basically a manual way of deciding what gets bundled with a file.
