### ISSUE TITLE
Allow loaders in import request

### ISSUE THREAD

**Issue by jquense** [webpack-contrib/less-loader#90]
Right now you can't make use of request loaders in the imports, we'd like to do this because we compile our less theme from a js file we share with the application so i'd like to do `@import 'theme-loader!theme.js'`, would ya'll be open to a PR, its a simple enough addition however it probably only works with the async branch since it needs to use `.loadModule` which (afaict) has no sync equivalent?

**Comment by cpsubrian** [comment]
@jquense I'm looking to get this functionality as well. I sorta liked something I saw in an issue here where you'd "opt-in" to webpack via something like:

```less
@import (module) 'path/to/module'; // webpack-resolved (no tilde required)
```

I'm totally ok with using/maintaining a fork to get this. Do you have some working code to start with or clues how I might implement this?

**Comment by jquense** [comment]
@cpsubrian https://github.com/jquense/less-loader/commit/b5ddf5e9005950322cbf1a76521a3698febb4575

**Comment by cpsubrian** [comment]
@jquense Awesome! Will parse through that and figure it out. Slowly learning how webpack loaders and whatnot work. Wrote a loader that looks for stuff like `@import them('colors')` and replaces it with a real path that goes through a fallback search. Unfortunately since that loader doesn't run on files that less imports, you can't use it more than one-level deep from a top level require().

**Comment by jhnns** [comment]
Starting with less-loader 4, this should work now. See https://github.com/webpack-contrib/less-loader#non-less-imports

**Comment by cpsubrian** [comment]
@jhnns Not sure this issue is resolved just yet. It seems like the same original issue is present where imports loaded inside imports are not run through webpack. I will try to fork and add a failing test case.

**Comment by cpsubrian** [comment]
@jhnns Made a PR that has the failing test case in #197. Hopefully that helps make the issue clearer.
