### ISSUE TITLE
Use "less" field in "package.json" if possible

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/less-loader#91]
It would be nice if this loader could use the "less" field in "package.json" which some projects use. See [bootstrap/package.json#L22](https://github.com/twbs/bootstrap/blob/master/package.json#L22) for an example.

We could write `@import "~bootstrap";` instead of `@import "~bootstrap/less/bootstrap";`. With the [omit-tilde-webpack-plugin](https://github.com/bholloway/omit-tilde-webpack-plugin) we could even write `@import "bootstrap";`.

(Maybe this can be manually done with [`resolve.packageMains`](https://webpack.github.io/docs/configuration.html#resolve-packagemains) and `resolve.extensions`, but it doesn't work for me.)

**Comment by jhnns** [comment]
Starting with less-loader 4 and [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields), this should work. Please re-open with a test-case if it doesn't work.

**Comment by guoerwei** [comment]
didn't work with scoped npm package

```less
@import "~@some-scope/some-style-module";
```

and get error: `Can't resolve "@some-scope/some-style-module.less" in ...`

**Comment by dobernike** [comment]
@guoerwei did you fix it?
