### ISSUE TITLE
Cannot import LESS files hosted remotely

### ISSUE THREAD

**Issue by leggomuhgreggo** [webpack-contrib/less-loader#95]
Greetings and thanks

Importing remotely hosted less files in either of the following formats:

```
@import  url("https://rawgit.com/twbs/bootstrap/master/less/bootstrap.less");
@import (less) url("https://rawgit.com/twbs/bootstrap/master/less/bootstrap.less");
```

triggers an error like this.

```
ERROR in ./~/css-loader!./~/less-loader!./styles/styles.less
Module build failed: Cannot resolve 'file' or 'directory' ./https://rawgit.com/twbs/bootstrap/master/less/bootstrap.less in /home/user/projects/less-loader-test/styles
 @ /home/user/projects/less-loader-test/styles/styles.less (line 1, column 0)
 near lines:

   @import (less) url("https://rawgit.com/twbs/bootstrap/master/less/bootstrap.less");

 @ ./styles/styles.less 4:14-117
```

[Here's this codepen](http://codepen.io/leggomuhgreggo/pen/QNRJaN), by way of demonstrating that the bootstrap.less file actually works

I have a reduced test case, which I can make available if it's helpful, but my guess is it will be easier to add a LESS file to the imports in the [imports-uri test](https://github.com/webpack/less-loader/blob/master/test/less/imports-url.less).

**Comment by evilebottnawi** [comment]
Same problem with:

```
@import (inline) url('https://fonts.googleapis.com/css?family=Berkshire+Swash|Chicle|Courgette|Lobster&display=swap');
```
