### ISSUE TITLE
less-loader will filter `\`.

### ISSUE THREAD

**Issue by weizongqi1990** [webpack-contrib/less-loader#96]
This is my less code:
`a {
   &:after {
      content: "\A";
      white-space: pre;
    }
  }`
This is compiled css code:
`a:after {
    content: "A";
    white-space: pre;
  }`

And I use `\\`,this is my less code:
`a {
   &:after {
      content: "\\A";
      white-space: pre;
    }
  }`
This is compiled css code:
`a:after {
    content: "\\A";
    white-space: pre;
  }`
Why filter single backslash？

**Comment by michael-ciniawsky** [comment]
Duplicate of #123
