### ISSUE TITLE
Can make the less @import file cache

### ISSUE THREAD

**Issue by monkindey** [webpack-contrib/less-loader#99]
when i exec the `webpack -w`
my less **`index.less`** file like that

``` less
@import "../common/common.less";
.area {
    ...rules
}
...
```

and the common.less

``` less
@import "constants.less";
@import "normalize.less";
@import "reset.less";
@import "util.less";
@import "shape.less";
@import "clockhand.less";
@import "header.less";
@import "nav.less";
@import "tools.less";
@import "changepassword.less";
@import "popup.less";
@import "font-awesome.less";
```

when i change the **`index.less`** ,
and the webpack will rebuild the common.less, but i didn't change the `common.less`

that's it

Thanks

**Comment by monkindey** [comment]
Was it a strange feature and closed it ?

**Comment by michael-ciniawsky** [comment]
The moment `less` encounters a `@import` it will process it, there is little we can do here unless less itself provides an option or caches recursive `@import`s by default :)

**Comment by monkindey** [comment]
Can we create a PR for this to less project ? Because `babel` and `babel-loader` have did and I think we can also do. What thought about you ?
